// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

public interface AccessControlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupsProtos.AccessControl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Who can modify the group title, avatar, disappearing messages timer
   * </pre>
   *
   * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
   * @return The enum numeric value on the wire for attributes.
   */
  int getAttributesValue();
  /**
   * <pre>
   * Who can modify the group title, avatar, disappearing messages timer
   * </pre>
   *
   * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
   * @return The attributes.
   */
  org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired getAttributes();

  /**
   * <pre>
   * Who can add people to the group
   * </pre>
   *
   * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
   * @return The enum numeric value on the wire for members.
   */
  int getMembersValue();
  /**
   * <pre>
   * Who can add people to the group
   * </pre>
   *
   * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
   * @return The members.
   */
  org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired getMembers();
}
