// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

/**
 * Protobuf type {@code GroupsProtos.AccessControl}
 */
public final class AccessControl extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GroupsProtos.AccessControl)
    AccessControlOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccessControl.newBuilder() to construct.
  private AccessControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccessControl() {
    attributes_ = 0;
    members_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new AccessControl();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccessControl(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            attributes_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            members_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_AccessControl_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_AccessControl_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.whispersystems.textsecuregcm.proto.AccessControl.class, org.whispersystems.textsecuregcm.proto.AccessControl.Builder.class);
  }

  /**
   * Protobuf enum {@code GroupsProtos.AccessControl.AccessRequired}
   */
  public enum AccessRequired
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * Anyone can make the modification, even if they're not in the group
     * </pre>
     *
     * <code>ANY = 1;</code>
     */
    ANY(1),
    /**
     * <pre>
     * Any group member can make the modification
     * </pre>
     *
     * <code>MEMBER = 2;</code>
     */
    MEMBER(2),
    /**
     * <pre>
     * Only administrators can make the modification
     * </pre>
     *
     * <code>ADMINISTRATOR = 3;</code>
     */
    ADMINISTRATOR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Anyone can make the modification, even if they're not in the group
     * </pre>
     *
     * <code>ANY = 1;</code>
     */
    public static final int ANY_VALUE = 1;
    /**
     * <pre>
     * Any group member can make the modification
     * </pre>
     *
     * <code>MEMBER = 2;</code>
     */
    public static final int MEMBER_VALUE = 2;
    /**
     * <pre>
     * Only administrators can make the modification
     * </pre>
     *
     * <code>ADMINISTRATOR = 3;</code>
     */
    public static final int ADMINISTRATOR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static AccessRequired valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AccessRequired forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return ANY;
        case 2: return MEMBER;
        case 3: return ADMINISTRATOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccessRequired>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AccessRequired> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccessRequired>() {
            public AccessRequired findValueByNumber(int number) {
              return AccessRequired.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.AccessControl.getDescriptor().getEnumTypes().get(0);
    }

    private static final AccessRequired[] VALUES = values();

    public static AccessRequired valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AccessRequired(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GroupsProtos.AccessControl.AccessRequired)
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 1;
  private int attributes_;
  /**
   * <pre>
   * Who can modify the group title, avatar, disappearing messages timer
   * </pre>
   *
   * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
   * @return The enum numeric value on the wire for attributes.
   */
  @Override public int getAttributesValue() {
    return attributes_;
  }
  /**
   * <pre>
   * Who can modify the group title, avatar, disappearing messages timer
   * </pre>
   *
   * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
   * @return The attributes.
   */
  @Override public org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired getAttributes() {
    @SuppressWarnings("deprecation")
    org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired result = org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.valueOf(attributes_);
    return result == null ? org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.UNRECOGNIZED : result;
  }

  public static final int MEMBERS_FIELD_NUMBER = 2;
  private int members_;
  /**
   * <pre>
   * Who can add people to the group
   * </pre>
   *
   * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
   * @return The enum numeric value on the wire for members.
   */
  @Override public int getMembersValue() {
    return members_;
  }
  /**
   * <pre>
   * Who can add people to the group
   * </pre>
   *
   * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
   * @return The members.
   */
  @Override public org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired getMembers() {
    @SuppressWarnings("deprecation")
    org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired result = org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.valueOf(members_);
    return result == null ? org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (attributes_ != org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      output.writeEnum(1, attributes_);
    }
    if (members_ != org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      output.writeEnum(2, members_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (attributes_ != org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, attributes_);
    }
    if (members_ != org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, members_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.whispersystems.textsecuregcm.proto.AccessControl)) {
      return super.equals(obj);
    }
    org.whispersystems.textsecuregcm.proto.AccessControl other = (org.whispersystems.textsecuregcm.proto.AccessControl) obj;

    if (attributes_ != other.attributes_) return false;
    if (members_ != other.members_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
    hash = (53 * hash) + attributes_;
    hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
    hash = (53 * hash) + members_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.AccessControl parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.whispersystems.textsecuregcm.proto.AccessControl prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GroupsProtos.AccessControl}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GroupsProtos.AccessControl)
      org.whispersystems.textsecuregcm.proto.AccessControlOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_AccessControl_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_AccessControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.proto.AccessControl.class, org.whispersystems.textsecuregcm.proto.AccessControl.Builder.class);
    }

    // Construct using org.whispersystems.textsecuregcm.proto.AccessControl.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      attributes_ = 0;

      members_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_AccessControl_descriptor;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.AccessControl getDefaultInstanceForType() {
      return org.whispersystems.textsecuregcm.proto.AccessControl.getDefaultInstance();
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.AccessControl build() {
      org.whispersystems.textsecuregcm.proto.AccessControl result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.AccessControl buildPartial() {
      org.whispersystems.textsecuregcm.proto.AccessControl result = new org.whispersystems.textsecuregcm.proto.AccessControl(this);
      result.attributes_ = attributes_;
      result.members_ = members_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.whispersystems.textsecuregcm.proto.AccessControl) {
        return mergeFrom((org.whispersystems.textsecuregcm.proto.AccessControl)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.whispersystems.textsecuregcm.proto.AccessControl other) {
      if (other == org.whispersystems.textsecuregcm.proto.AccessControl.getDefaultInstance()) return this;
      if (other.attributes_ != 0) {
        setAttributesValue(other.getAttributesValue());
      }
      if (other.members_ != 0) {
        setMembersValue(other.getMembersValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.whispersystems.textsecuregcm.proto.AccessControl parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.whispersystems.textsecuregcm.proto.AccessControl) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int attributes_ = 0;
    /**
     * <pre>
     * Who can modify the group title, avatar, disappearing messages timer
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
     * @return The enum numeric value on the wire for attributes.
     */
    @Override public int getAttributesValue() {
      return attributes_;
    }
    /**
     * <pre>
     * Who can modify the group title, avatar, disappearing messages timer
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
     * @param value The enum numeric value on the wire for attributes to set.
     * @return This builder for chaining.
     */
    public Builder setAttributesValue(int value) {
      
      attributes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Who can modify the group title, avatar, disappearing messages timer
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
     * @return The attributes.
     */
    @Override
    public org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired getAttributes() {
      @SuppressWarnings("deprecation")
      org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired result = org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.valueOf(attributes_);
      return result == null ? org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Who can modify the group title, avatar, disappearing messages timer
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
     * @param value The attributes to set.
     * @return This builder for chaining.
     */
    public Builder setAttributes(org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      attributes_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Who can modify the group title, avatar, disappearing messages timer
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired attributes = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttributes() {
      
      attributes_ = 0;
      onChanged();
      return this;
    }

    private int members_ = 0;
    /**
     * <pre>
     * Who can add people to the group
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
     * @return The enum numeric value on the wire for members.
     */
    @Override public int getMembersValue() {
      return members_;
    }
    /**
     * <pre>
     * Who can add people to the group
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
     * @param value The enum numeric value on the wire for members to set.
     * @return This builder for chaining.
     */
    public Builder setMembersValue(int value) {
      
      members_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Who can add people to the group
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
     * @return The members.
     */
    @Override
    public org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired getMembers() {
      @SuppressWarnings("deprecation")
      org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired result = org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.valueOf(members_);
      return result == null ? org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Who can add people to the group
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
     * @param value The members to set.
     * @return This builder for chaining.
     */
    public Builder setMembers(org.whispersystems.textsecuregcm.proto.AccessControl.AccessRequired value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      members_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Who can add people to the group
     * </pre>
     *
     * <code>.GroupsProtos.AccessControl.AccessRequired members = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMembers() {
      
      members_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GroupsProtos.AccessControl)
  }

  // @@protoc_insertion_point(class_scope:GroupsProtos.AccessControl)
  private static final org.whispersystems.textsecuregcm.proto.AccessControl DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.proto.AccessControl();
  }

  public static org.whispersystems.textsecuregcm.proto.AccessControl getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccessControl>
      PARSER = new com.google.protobuf.AbstractParser<AccessControl>() {
    @Override
    public AccessControl parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AccessControl(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccessControl> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AccessControl> getParserForType() {
    return PARSER;
  }

  @Override
  public org.whispersystems.textsecuregcm.proto.AccessControl getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

