// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

public interface AvatarUploadAttributesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupsProtos.AvatarUploadAttributes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string credential = 2;</code>
   * @return The credential.
   */
  String getCredential();
  /**
   * <code>string credential = 2;</code>
   * @return The bytes for credential.
   */
  com.google.protobuf.ByteString
      getCredentialBytes();

  /**
   * <code>string acl = 3;</code>
   * @return The acl.
   */
  String getAcl();
  /**
   * <code>string acl = 3;</code>
   * @return The bytes for acl.
   */
  com.google.protobuf.ByteString
      getAclBytes();

  /**
   * <code>string algorithm = 4;</code>
   * @return The algorithm.
   */
  String getAlgorithm();
  /**
   * <code>string algorithm = 4;</code>
   * @return The bytes for algorithm.
   */
  com.google.protobuf.ByteString
      getAlgorithmBytes();

  /**
   * <code>string date = 5;</code>
   * @return The date.
   */
  String getDate();
  /**
   * <code>string date = 5;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string policy = 6;</code>
   * @return The policy.
   */
  String getPolicy();
  /**
   * <code>string policy = 6;</code>
   * @return The bytes for policy.
   */
  com.google.protobuf.ByteString
      getPolicyBytes();

  /**
   * <code>string signature = 7;</code>
   * @return The signature.
   */
  String getSignature();
  /**
   * <code>string signature = 7;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();
}
