// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

public interface GroupChangesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupsProtos.GroupChanges)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  java.util.List<org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState>
      getGroupChangesList();
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState getGroupChanges(int index);
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  int getGroupChangesCount();
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  java.util.List<? extends org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder>
      getGroupChangesOrBuilderList();
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder getGroupChangesOrBuilder(
      int index);
}
