// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

public interface GroupAttributeBlobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupsProtos.GroupAttributeBlob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>bytes avatar = 2;</code>
   * @return The avatar.
   */
  com.google.protobuf.ByteString getAvatar();

  /**
   * <code>uint32 disappearingMessagesDuration = 3;</code>
   * @return The disappearingMessagesDuration.
   */
  int getDisappearingMessagesDuration();

  public org.whispersystems.textsecuregcm.proto.GroupAttributeBlob.ContentCase getContentCase();
}
