// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

/**
 * Protobuf type {@code GroupsProtos.Group}
 */
public final class Group extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GroupsProtos.Group)
    GroupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Group.newBuilder() to construct.
  private Group(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Group() {
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
    title_ = com.google.protobuf.ByteString.EMPTY;
    avatar_ = "";
    disappearingMessagesTimer_ = com.google.protobuf.ByteString.EMPTY;
    members_ = java.util.Collections.emptyList();
    pendingMembers_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Group();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Group(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            publicKey_ = input.readBytes();
            break;
          }
          case 18: {

            title_ = input.readBytes();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            avatar_ = s;
            break;
          }
          case 34: {

            disappearingMessagesTimer_ = input.readBytes();
            break;
          }
          case 42: {
            org.whispersystems.textsecuregcm.proto.AccessControl.Builder subBuilder = null;
            if (accessControl_ != null) {
              subBuilder = accessControl_.toBuilder();
            }
            accessControl_ = input.readMessage(org.whispersystems.textsecuregcm.proto.AccessControl.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(accessControl_);
              accessControl_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            revision_ = input.readUInt32();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              members_ = new java.util.ArrayList<org.whispersystems.textsecuregcm.proto.Member>();
              mutable_bitField0_ |= 0x00000001;
            }
            members_.add(
                input.readMessage(org.whispersystems.textsecuregcm.proto.Member.parser(), extensionRegistry));
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              pendingMembers_ = new java.util.ArrayList<org.whispersystems.textsecuregcm.proto.PendingMember>();
              mutable_bitField0_ |= 0x00000002;
            }
            pendingMembers_.add(
                input.readMessage(org.whispersystems.textsecuregcm.proto.PendingMember.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        members_ = java.util.Collections.unmodifiableList(members_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        pendingMembers_ = java.util.Collections.unmodifiableList(pendingMembers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Group_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Group_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.whispersystems.textsecuregcm.proto.Group.class, org.whispersystems.textsecuregcm.proto.Group.Builder.class);
  }

  public static final int PUBLICKEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <pre>
   * GroupPublicParams
   * </pre>
   *
   * <code>bytes publicKey = 1;</code>
   * @return The publicKey.
   */
  @Override
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString title_;
  /**
   * <pre>
   * Encrypted title
   * </pre>
   *
   * <code>bytes title = 2;</code>
   * @return The title.
   */
  @Override
  public com.google.protobuf.ByteString getTitle() {
    return title_;
  }

  public static final int AVATAR_FIELD_NUMBER = 3;
  private volatile Object avatar_;
  /**
   * <pre>
   * Pointer to encrypted avatar (‘key’ from AvatarUploadAttributes)
   * </pre>
   *
   * <code>string avatar = 3;</code>
   * @return The avatar.
   */
  @Override
  public String getAvatar() {
    Object ref = avatar_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Pointer to encrypted avatar (‘key’ from AvatarUploadAttributes)
   * </pre>
   *
   * <code>string avatar = 3;</code>
   * @return The bytes for avatar.
   */
  @Override
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    Object ref = avatar_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISAPPEARINGMESSAGESTIMER_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString disappearingMessagesTimer_;
  /**
   * <pre>
   * Encrypted timer
   * </pre>
   *
   * <code>bytes disappearingMessagesTimer = 4;</code>
   * @return The disappearingMessagesTimer.
   */
  @Override
  public com.google.protobuf.ByteString getDisappearingMessagesTimer() {
    return disappearingMessagesTimer_;
  }

  public static final int ACCESSCONTROL_FIELD_NUMBER = 5;
  private org.whispersystems.textsecuregcm.proto.AccessControl accessControl_;
  /**
   * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
   * @return Whether the accessControl field is set.
   */
  @Override
  public boolean hasAccessControl() {
    return accessControl_ != null;
  }
  /**
   * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
   * @return The accessControl.
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.AccessControl getAccessControl() {
    return accessControl_ == null ? org.whispersystems.textsecuregcm.proto.AccessControl.getDefaultInstance() : accessControl_;
  }
  /**
   * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.AccessControlOrBuilder getAccessControlOrBuilder() {
    return getAccessControl();
  }

  public static final int REVISION_FIELD_NUMBER = 6;
  private int revision_;
  /**
   * <pre>
   * Current group revision number
   * </pre>
   *
   * <code>uint32 revision = 6;</code>
   * @return The revision.
   */
  @Override
  public int getRevision() {
    return revision_;
  }

  public static final int MEMBERS_FIELD_NUMBER = 7;
  private java.util.List<org.whispersystems.textsecuregcm.proto.Member> members_;
  /**
   * <code>repeated .GroupsProtos.Member members = 7;</code>
   */
  @Override
  public java.util.List<org.whispersystems.textsecuregcm.proto.Member> getMembersList() {
    return members_;
  }
  /**
   * <code>repeated .GroupsProtos.Member members = 7;</code>
   */
  @Override
  public java.util.List<? extends org.whispersystems.textsecuregcm.proto.MemberOrBuilder>
      getMembersOrBuilderList() {
    return members_;
  }
  /**
   * <code>repeated .GroupsProtos.Member members = 7;</code>
   */
  @Override
  public int getMembersCount() {
    return members_.size();
  }
  /**
   * <code>repeated .GroupsProtos.Member members = 7;</code>
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.Member getMembers(int index) {
    return members_.get(index);
  }
  /**
   * <code>repeated .GroupsProtos.Member members = 7;</code>
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.MemberOrBuilder getMembersOrBuilder(
      int index) {
    return members_.get(index);
  }

  public static final int PENDINGMEMBERS_FIELD_NUMBER = 8;
  private java.util.List<org.whispersystems.textsecuregcm.proto.PendingMember> pendingMembers_;
  /**
   * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
   */
  @Override
  public java.util.List<org.whispersystems.textsecuregcm.proto.PendingMember> getPendingMembersList() {
    return pendingMembers_;
  }
  /**
   * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
   */
  @Override
  public java.util.List<? extends org.whispersystems.textsecuregcm.proto.PendingMemberOrBuilder>
      getPendingMembersOrBuilderList() {
    return pendingMembers_;
  }
  /**
   * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
   */
  @Override
  public int getPendingMembersCount() {
    return pendingMembers_.size();
  }
  /**
   * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.PendingMember getPendingMembers(int index) {
    return pendingMembers_.get(index);
  }
  /**
   * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.PendingMemberOrBuilder getPendingMembersOrBuilder(
      int index) {
    return pendingMembers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!publicKey_.isEmpty()) {
      output.writeBytes(1, publicKey_);
    }
    if (!title_.isEmpty()) {
      output.writeBytes(2, title_);
    }
    if (!getAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
    }
    if (!disappearingMessagesTimer_.isEmpty()) {
      output.writeBytes(4, disappearingMessagesTimer_);
    }
    if (accessControl_ != null) {
      output.writeMessage(5, getAccessControl());
    }
    if (revision_ != 0) {
      output.writeUInt32(6, revision_);
    }
    for (int i = 0; i < members_.size(); i++) {
      output.writeMessage(7, members_.get(i));
    }
    for (int i = 0; i < pendingMembers_.size(); i++) {
      output.writeMessage(8, pendingMembers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!publicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, publicKey_);
    }
    if (!title_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, title_);
    }
    if (!getAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
    }
    if (!disappearingMessagesTimer_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, disappearingMessagesTimer_);
    }
    if (accessControl_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAccessControl());
    }
    if (revision_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, revision_);
    }
    for (int i = 0; i < members_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, members_.get(i));
    }
    for (int i = 0; i < pendingMembers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, pendingMembers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.whispersystems.textsecuregcm.proto.Group)) {
      return super.equals(obj);
    }
    org.whispersystems.textsecuregcm.proto.Group other = (org.whispersystems.textsecuregcm.proto.Group) obj;

    if (!getPublicKey()
        .equals(other.getPublicKey())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getAvatar()
        .equals(other.getAvatar())) return false;
    if (!getDisappearingMessagesTimer()
        .equals(other.getDisappearingMessagesTimer())) return false;
    if (hasAccessControl() != other.hasAccessControl()) return false;
    if (hasAccessControl()) {
      if (!getAccessControl()
          .equals(other.getAccessControl())) return false;
    }
    if (getRevision()
        != other.getRevision()) return false;
    if (!getMembersList()
        .equals(other.getMembersList())) return false;
    if (!getPendingMembersList()
        .equals(other.getPendingMembersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPublicKey().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + DISAPPEARINGMESSAGESTIMER_FIELD_NUMBER;
    hash = (53 * hash) + getDisappearingMessagesTimer().hashCode();
    if (hasAccessControl()) {
      hash = (37 * hash) + ACCESSCONTROL_FIELD_NUMBER;
      hash = (53 * hash) + getAccessControl().hashCode();
    }
    hash = (37 * hash) + REVISION_FIELD_NUMBER;
    hash = (53 * hash) + getRevision();
    if (getMembersCount() > 0) {
      hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMembersList().hashCode();
    }
    if (getPendingMembersCount() > 0) {
      hash = (37 * hash) + PENDINGMEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getPendingMembersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.Group parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.whispersystems.textsecuregcm.proto.Group prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GroupsProtos.Group}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GroupsProtos.Group)
      org.whispersystems.textsecuregcm.proto.GroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Group_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Group_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.proto.Group.class, org.whispersystems.textsecuregcm.proto.Group.Builder.class);
    }

    // Construct using org.whispersystems.textsecuregcm.proto.Group.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMembersFieldBuilder();
        getPendingMembersFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      publicKey_ = com.google.protobuf.ByteString.EMPTY;

      title_ = com.google.protobuf.ByteString.EMPTY;

      avatar_ = "";

      disappearingMessagesTimer_ = com.google.protobuf.ByteString.EMPTY;

      if (accessControlBuilder_ == null) {
        accessControl_ = null;
      } else {
        accessControl_ = null;
        accessControlBuilder_ = null;
      }
      revision_ = 0;

      if (membersBuilder_ == null) {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        membersBuilder_.clear();
      }
      if (pendingMembersBuilder_ == null) {
        pendingMembers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        pendingMembersBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Group_descriptor;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.Group getDefaultInstanceForType() {
      return org.whispersystems.textsecuregcm.proto.Group.getDefaultInstance();
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.Group build() {
      org.whispersystems.textsecuregcm.proto.Group result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.Group buildPartial() {
      org.whispersystems.textsecuregcm.proto.Group result = new org.whispersystems.textsecuregcm.proto.Group(this);
      int from_bitField0_ = bitField0_;
      result.publicKey_ = publicKey_;
      result.title_ = title_;
      result.avatar_ = avatar_;
      result.disappearingMessagesTimer_ = disappearingMessagesTimer_;
      if (accessControlBuilder_ == null) {
        result.accessControl_ = accessControl_;
      } else {
        result.accessControl_ = accessControlBuilder_.build();
      }
      result.revision_ = revision_;
      if (membersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          members_ = java.util.Collections.unmodifiableList(members_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.members_ = members_;
      } else {
        result.members_ = membersBuilder_.build();
      }
      if (pendingMembersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          pendingMembers_ = java.util.Collections.unmodifiableList(pendingMembers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.pendingMembers_ = pendingMembers_;
      } else {
        result.pendingMembers_ = pendingMembersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.whispersystems.textsecuregcm.proto.Group) {
        return mergeFrom((org.whispersystems.textsecuregcm.proto.Group)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.whispersystems.textsecuregcm.proto.Group other) {
      if (other == org.whispersystems.textsecuregcm.proto.Group.getDefaultInstance()) return this;
      if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
        setPublicKey(other.getPublicKey());
      }
      if (other.getTitle() != com.google.protobuf.ByteString.EMPTY) {
        setTitle(other.getTitle());
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        onChanged();
      }
      if (other.getDisappearingMessagesTimer() != com.google.protobuf.ByteString.EMPTY) {
        setDisappearingMessagesTimer(other.getDisappearingMessagesTimer());
      }
      if (other.hasAccessControl()) {
        mergeAccessControl(other.getAccessControl());
      }
      if (other.getRevision() != 0) {
        setRevision(other.getRevision());
      }
      if (membersBuilder_ == null) {
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
      } else {
        if (!other.members_.isEmpty()) {
          if (membersBuilder_.isEmpty()) {
            membersBuilder_.dispose();
            membersBuilder_ = null;
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000001);
            membersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembersFieldBuilder() : null;
          } else {
            membersBuilder_.addAllMessages(other.members_);
          }
        }
      }
      if (pendingMembersBuilder_ == null) {
        if (!other.pendingMembers_.isEmpty()) {
          if (pendingMembers_.isEmpty()) {
            pendingMembers_ = other.pendingMembers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePendingMembersIsMutable();
            pendingMembers_.addAll(other.pendingMembers_);
          }
          onChanged();
        }
      } else {
        if (!other.pendingMembers_.isEmpty()) {
          if (pendingMembersBuilder_.isEmpty()) {
            pendingMembersBuilder_.dispose();
            pendingMembersBuilder_ = null;
            pendingMembers_ = other.pendingMembers_;
            bitField0_ = (bitField0_ & ~0x00000002);
            pendingMembersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPendingMembersFieldBuilder() : null;
          } else {
            pendingMembersBuilder_.addAllMessages(other.pendingMembers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.whispersystems.textsecuregcm.proto.Group parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.whispersystems.textsecuregcm.proto.Group) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * GroupPublicParams
     * </pre>
     *
     * <code>bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    @Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }
    /**
     * <pre>
     * GroupPublicParams
     * </pre>
     *
     * <code>bytes publicKey = 1;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      publicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * GroupPublicParams
     * </pre>
     *
     * <code>bytes publicKey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      
      publicKey_ = getDefaultInstance().getPublicKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString title_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Encrypted title
     * </pre>
     *
     * <code>bytes title = 2;</code>
     * @return The title.
     */
    @Override
    public com.google.protobuf.ByteString getTitle() {
      return title_;
    }
    /**
     * <pre>
     * Encrypted title
     * </pre>
     *
     * <code>bytes title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encrypted title
     * </pre>
     *
     * <code>bytes title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }

    private Object avatar_ = "";
    /**
     * <pre>
     * Pointer to encrypted avatar (‘key’ from AvatarUploadAttributes)
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return The avatar.
     */
    public String getAvatar() {
      Object ref = avatar_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Pointer to encrypted avatar (‘key’ from AvatarUploadAttributes)
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return The bytes for avatar.
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Pointer to encrypted avatar (‘key’ from AvatarUploadAttributes)
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @param value The avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatar(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      avatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pointer to encrypted avatar (‘key’ from AvatarUploadAttributes)
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatar() {
      
      avatar_ = getDefaultInstance().getAvatar();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pointer to encrypted avatar (‘key’ from AvatarUploadAttributes)
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @param value The bytes for avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      avatar_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString disappearingMessagesTimer_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Encrypted timer
     * </pre>
     *
     * <code>bytes disappearingMessagesTimer = 4;</code>
     * @return The disappearingMessagesTimer.
     */
    @Override
    public com.google.protobuf.ByteString getDisappearingMessagesTimer() {
      return disappearingMessagesTimer_;
    }
    /**
     * <pre>
     * Encrypted timer
     * </pre>
     *
     * <code>bytes disappearingMessagesTimer = 4;</code>
     * @param value The disappearingMessagesTimer to set.
     * @return This builder for chaining.
     */
    public Builder setDisappearingMessagesTimer(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      disappearingMessagesTimer_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encrypted timer
     * </pre>
     *
     * <code>bytes disappearingMessagesTimer = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisappearingMessagesTimer() {
      
      disappearingMessagesTimer_ = getDefaultInstance().getDisappearingMessagesTimer();
      onChanged();
      return this;
    }

    private org.whispersystems.textsecuregcm.proto.AccessControl accessControl_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.AccessControl, org.whispersystems.textsecuregcm.proto.AccessControl.Builder, org.whispersystems.textsecuregcm.proto.AccessControlOrBuilder> accessControlBuilder_;
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     * @return Whether the accessControl field is set.
     */
    public boolean hasAccessControl() {
      return accessControlBuilder_ != null || accessControl_ != null;
    }
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     * @return The accessControl.
     */
    public org.whispersystems.textsecuregcm.proto.AccessControl getAccessControl() {
      if (accessControlBuilder_ == null) {
        return accessControl_ == null ? org.whispersystems.textsecuregcm.proto.AccessControl.getDefaultInstance() : accessControl_;
      } else {
        return accessControlBuilder_.getMessage();
      }
    }
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     */
    public Builder setAccessControl(org.whispersystems.textsecuregcm.proto.AccessControl value) {
      if (accessControlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accessControl_ = value;
        onChanged();
      } else {
        accessControlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     */
    public Builder setAccessControl(
        org.whispersystems.textsecuregcm.proto.AccessControl.Builder builderForValue) {
      if (accessControlBuilder_ == null) {
        accessControl_ = builderForValue.build();
        onChanged();
      } else {
        accessControlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     */
    public Builder mergeAccessControl(org.whispersystems.textsecuregcm.proto.AccessControl value) {
      if (accessControlBuilder_ == null) {
        if (accessControl_ != null) {
          accessControl_ =
            org.whispersystems.textsecuregcm.proto.AccessControl.newBuilder(accessControl_).mergeFrom(value).buildPartial();
        } else {
          accessControl_ = value;
        }
        onChanged();
      } else {
        accessControlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     */
    public Builder clearAccessControl() {
      if (accessControlBuilder_ == null) {
        accessControl_ = null;
        onChanged();
      } else {
        accessControl_ = null;
        accessControlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     */
    public org.whispersystems.textsecuregcm.proto.AccessControl.Builder getAccessControlBuilder() {
      
      onChanged();
      return getAccessControlFieldBuilder().getBuilder();
    }
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     */
    public org.whispersystems.textsecuregcm.proto.AccessControlOrBuilder getAccessControlOrBuilder() {
      if (accessControlBuilder_ != null) {
        return accessControlBuilder_.getMessageOrBuilder();
      } else {
        return accessControl_ == null ?
            org.whispersystems.textsecuregcm.proto.AccessControl.getDefaultInstance() : accessControl_;
      }
    }
    /**
     * <code>.GroupsProtos.AccessControl accessControl = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.AccessControl, org.whispersystems.textsecuregcm.proto.AccessControl.Builder, org.whispersystems.textsecuregcm.proto.AccessControlOrBuilder>
        getAccessControlFieldBuilder() {
      if (accessControlBuilder_ == null) {
        accessControlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.whispersystems.textsecuregcm.proto.AccessControl, org.whispersystems.textsecuregcm.proto.AccessControl.Builder, org.whispersystems.textsecuregcm.proto.AccessControlOrBuilder>(
                getAccessControl(),
                getParentForChildren(),
                isClean());
        accessControl_ = null;
      }
      return accessControlBuilder_;
    }

    private int revision_ ;
    /**
     * <pre>
     * Current group revision number
     * </pre>
     *
     * <code>uint32 revision = 6;</code>
     * @return The revision.
     */
    @Override
    public int getRevision() {
      return revision_;
    }
    /**
     * <pre>
     * Current group revision number
     * </pre>
     *
     * <code>uint32 revision = 6;</code>
     * @param value The revision to set.
     * @return This builder for chaining.
     */
    public Builder setRevision(int value) {
      
      revision_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current group revision number
     * </pre>
     *
     * <code>uint32 revision = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevision() {
      
      revision_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.whispersystems.textsecuregcm.proto.Member> members_ =
      java.util.Collections.emptyList();
    private void ensureMembersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        members_ = new java.util.ArrayList<org.whispersystems.textsecuregcm.proto.Member>(members_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.Member, org.whispersystems.textsecuregcm.proto.Member.Builder, org.whispersystems.textsecuregcm.proto.MemberOrBuilder> membersBuilder_;

    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public java.util.List<org.whispersystems.textsecuregcm.proto.Member> getMembersList() {
      if (membersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(members_);
      } else {
        return membersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public int getMembersCount() {
      if (membersBuilder_ == null) {
        return members_.size();
      } else {
        return membersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public org.whispersystems.textsecuregcm.proto.Member getMembers(int index) {
      if (membersBuilder_ == null) {
        return members_.get(index);
      } else {
        return membersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder setMembers(
        int index, org.whispersystems.textsecuregcm.proto.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
      } else {
        membersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder setMembers(
        int index, org.whispersystems.textsecuregcm.proto.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.set(index, builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder addMembers(org.whispersystems.textsecuregcm.proto.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.add(value);
        onChanged();
      } else {
        membersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder addMembers(
        int index, org.whispersystems.textsecuregcm.proto.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.add(index, value);
        onChanged();
      } else {
        membersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder addMembers(
        org.whispersystems.textsecuregcm.proto.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.add(builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder addMembers(
        int index, org.whispersystems.textsecuregcm.proto.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.add(index, builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder addAllMembers(
        Iterable<? extends org.whispersystems.textsecuregcm.proto.Member> values) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
      } else {
        membersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder clearMembers() {
      if (membersBuilder_ == null) {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        membersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public Builder removeMembers(int index) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.remove(index);
        onChanged();
      } else {
        membersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public org.whispersystems.textsecuregcm.proto.Member.Builder getMembersBuilder(
        int index) {
      return getMembersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public org.whispersystems.textsecuregcm.proto.MemberOrBuilder getMembersOrBuilder(
        int index) {
      if (membersBuilder_ == null) {
        return members_.get(index);  } else {
        return membersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public java.util.List<? extends org.whispersystems.textsecuregcm.proto.MemberOrBuilder>
         getMembersOrBuilderList() {
      if (membersBuilder_ != null) {
        return membersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(members_);
      }
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public org.whispersystems.textsecuregcm.proto.Member.Builder addMembersBuilder() {
      return getMembersFieldBuilder().addBuilder(
          org.whispersystems.textsecuregcm.proto.Member.getDefaultInstance());
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public org.whispersystems.textsecuregcm.proto.Member.Builder addMembersBuilder(
        int index) {
      return getMembersFieldBuilder().addBuilder(
          index, org.whispersystems.textsecuregcm.proto.Member.getDefaultInstance());
    }
    /**
     * <code>repeated .GroupsProtos.Member members = 7;</code>
     */
    public java.util.List<org.whispersystems.textsecuregcm.proto.Member.Builder>
         getMembersBuilderList() {
      return getMembersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.Member, org.whispersystems.textsecuregcm.proto.Member.Builder, org.whispersystems.textsecuregcm.proto.MemberOrBuilder>
        getMembersFieldBuilder() {
      if (membersBuilder_ == null) {
        membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.whispersystems.textsecuregcm.proto.Member, org.whispersystems.textsecuregcm.proto.Member.Builder, org.whispersystems.textsecuregcm.proto.MemberOrBuilder>(
                members_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        members_ = null;
      }
      return membersBuilder_;
    }

    private java.util.List<org.whispersystems.textsecuregcm.proto.PendingMember> pendingMembers_ =
      java.util.Collections.emptyList();
    private void ensurePendingMembersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        pendingMembers_ = new java.util.ArrayList<org.whispersystems.textsecuregcm.proto.PendingMember>(pendingMembers_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.PendingMember, org.whispersystems.textsecuregcm.proto.PendingMember.Builder, org.whispersystems.textsecuregcm.proto.PendingMemberOrBuilder> pendingMembersBuilder_;

    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public java.util.List<org.whispersystems.textsecuregcm.proto.PendingMember> getPendingMembersList() {
      if (pendingMembersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pendingMembers_);
      } else {
        return pendingMembersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public int getPendingMembersCount() {
      if (pendingMembersBuilder_ == null) {
        return pendingMembers_.size();
      } else {
        return pendingMembersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public org.whispersystems.textsecuregcm.proto.PendingMember getPendingMembers(int index) {
      if (pendingMembersBuilder_ == null) {
        return pendingMembers_.get(index);
      } else {
        return pendingMembersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder setPendingMembers(
        int index, org.whispersystems.textsecuregcm.proto.PendingMember value) {
      if (pendingMembersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePendingMembersIsMutable();
        pendingMembers_.set(index, value);
        onChanged();
      } else {
        pendingMembersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder setPendingMembers(
        int index, org.whispersystems.textsecuregcm.proto.PendingMember.Builder builderForValue) {
      if (pendingMembersBuilder_ == null) {
        ensurePendingMembersIsMutable();
        pendingMembers_.set(index, builderForValue.build());
        onChanged();
      } else {
        pendingMembersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder addPendingMembers(org.whispersystems.textsecuregcm.proto.PendingMember value) {
      if (pendingMembersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePendingMembersIsMutable();
        pendingMembers_.add(value);
        onChanged();
      } else {
        pendingMembersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder addPendingMembers(
        int index, org.whispersystems.textsecuregcm.proto.PendingMember value) {
      if (pendingMembersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePendingMembersIsMutable();
        pendingMembers_.add(index, value);
        onChanged();
      } else {
        pendingMembersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder addPendingMembers(
        org.whispersystems.textsecuregcm.proto.PendingMember.Builder builderForValue) {
      if (pendingMembersBuilder_ == null) {
        ensurePendingMembersIsMutable();
        pendingMembers_.add(builderForValue.build());
        onChanged();
      } else {
        pendingMembersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder addPendingMembers(
        int index, org.whispersystems.textsecuregcm.proto.PendingMember.Builder builderForValue) {
      if (pendingMembersBuilder_ == null) {
        ensurePendingMembersIsMutable();
        pendingMembers_.add(index, builderForValue.build());
        onChanged();
      } else {
        pendingMembersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder addAllPendingMembers(
        Iterable<? extends org.whispersystems.textsecuregcm.proto.PendingMember> values) {
      if (pendingMembersBuilder_ == null) {
        ensurePendingMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pendingMembers_);
        onChanged();
      } else {
        pendingMembersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder clearPendingMembers() {
      if (pendingMembersBuilder_ == null) {
        pendingMembers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        pendingMembersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public Builder removePendingMembers(int index) {
      if (pendingMembersBuilder_ == null) {
        ensurePendingMembersIsMutable();
        pendingMembers_.remove(index);
        onChanged();
      } else {
        pendingMembersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public org.whispersystems.textsecuregcm.proto.PendingMember.Builder getPendingMembersBuilder(
        int index) {
      return getPendingMembersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public org.whispersystems.textsecuregcm.proto.PendingMemberOrBuilder getPendingMembersOrBuilder(
        int index) {
      if (pendingMembersBuilder_ == null) {
        return pendingMembers_.get(index);  } else {
        return pendingMembersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public java.util.List<? extends org.whispersystems.textsecuregcm.proto.PendingMemberOrBuilder>
         getPendingMembersOrBuilderList() {
      if (pendingMembersBuilder_ != null) {
        return pendingMembersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pendingMembers_);
      }
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public org.whispersystems.textsecuregcm.proto.PendingMember.Builder addPendingMembersBuilder() {
      return getPendingMembersFieldBuilder().addBuilder(
          org.whispersystems.textsecuregcm.proto.PendingMember.getDefaultInstance());
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public org.whispersystems.textsecuregcm.proto.PendingMember.Builder addPendingMembersBuilder(
        int index) {
      return getPendingMembersFieldBuilder().addBuilder(
          index, org.whispersystems.textsecuregcm.proto.PendingMember.getDefaultInstance());
    }
    /**
     * <code>repeated .GroupsProtos.PendingMember pendingMembers = 8;</code>
     */
    public java.util.List<org.whispersystems.textsecuregcm.proto.PendingMember.Builder>
         getPendingMembersBuilderList() {
      return getPendingMembersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.PendingMember, org.whispersystems.textsecuregcm.proto.PendingMember.Builder, org.whispersystems.textsecuregcm.proto.PendingMemberOrBuilder>
        getPendingMembersFieldBuilder() {
      if (pendingMembersBuilder_ == null) {
        pendingMembersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.whispersystems.textsecuregcm.proto.PendingMember, org.whispersystems.textsecuregcm.proto.PendingMember.Builder, org.whispersystems.textsecuregcm.proto.PendingMemberOrBuilder>(
                pendingMembers_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        pendingMembers_ = null;
      }
      return pendingMembersBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GroupsProtos.Group)
  }

  // @@protoc_insertion_point(class_scope:GroupsProtos.Group)
  private static final org.whispersystems.textsecuregcm.proto.Group DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.proto.Group();
  }

  public static org.whispersystems.textsecuregcm.proto.Group getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Group>
      PARSER = new com.google.protobuf.AbstractParser<Group>() {
    @Override
    public Group parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Group(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Group> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Group> getParserForType() {
    return PARSER;
  }

  @Override
  public org.whispersystems.textsecuregcm.proto.Group getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

