// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

/**
 * Protobuf type {@code GroupsProtos.GroupChanges}
 */
public final class GroupChanges extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GroupsProtos.GroupChanges)
    GroupChangesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GroupChanges.newBuilder() to construct.
  private GroupChanges(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupChanges() {
    groupChanges_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GroupChanges();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GroupChanges(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              groupChanges_ = new java.util.ArrayList<org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState>();
              mutable_bitField0_ |= 0x00000001;
            }
            groupChanges_.add(
                input.readMessage(org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        groupChanges_ = java.util.Collections.unmodifiableList(groupChanges_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.whispersystems.textsecuregcm.proto.GroupChanges.class, org.whispersystems.textsecuregcm.proto.GroupChanges.Builder.class);
  }

  public interface GroupChangeStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GroupsProtos.GroupChanges.GroupChangeState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
     * @return Whether the groupChange field is set.
     */
    boolean hasGroupChange();
    /**
     * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
     * @return The groupChange.
     */
    org.whispersystems.textsecuregcm.proto.GroupChange getGroupChange();
    /**
     * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
     */
    org.whispersystems.textsecuregcm.proto.GroupChangeOrBuilder getGroupChangeOrBuilder();

    /**
     * <code>.GroupsProtos.Group groupState = 2;</code>
     * @return Whether the groupState field is set.
     */
    boolean hasGroupState();
    /**
     * <code>.GroupsProtos.Group groupState = 2;</code>
     * @return The groupState.
     */
    org.whispersystems.textsecuregcm.proto.Group getGroupState();
    /**
     * <code>.GroupsProtos.Group groupState = 2;</code>
     */
    org.whispersystems.textsecuregcm.proto.GroupOrBuilder getGroupStateOrBuilder();
  }
  /**
   * Protobuf type {@code GroupsProtos.GroupChanges.GroupChangeState}
   */
  public static final class GroupChangeState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GroupsProtos.GroupChanges.GroupChangeState)
      GroupChangeStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GroupChangeState.newBuilder() to construct.
    private GroupChangeState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupChangeState() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GroupChangeState();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GroupChangeState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.whispersystems.textsecuregcm.proto.GroupChange.Builder subBuilder = null;
              if (groupChange_ != null) {
                subBuilder = groupChange_.toBuilder();
              }
              groupChange_ = input.readMessage(org.whispersystems.textsecuregcm.proto.GroupChange.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(groupChange_);
                groupChange_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.whispersystems.textsecuregcm.proto.Group.Builder subBuilder = null;
              if (groupState_ != null) {
                subBuilder = groupState_.toBuilder();
              }
              groupState_ = input.readMessage(org.whispersystems.textsecuregcm.proto.Group.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(groupState_);
                groupState_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_GroupChangeState_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_GroupChangeState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.class, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder.class);
    }

    public static final int GROUPCHANGE_FIELD_NUMBER = 1;
    private org.whispersystems.textsecuregcm.proto.GroupChange groupChange_;
    /**
     * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
     * @return Whether the groupChange field is set.
     */
    @Override
    public boolean hasGroupChange() {
      return groupChange_ != null;
    }
    /**
     * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
     * @return The groupChange.
     */
    @Override
    public org.whispersystems.textsecuregcm.proto.GroupChange getGroupChange() {
      return groupChange_ == null ? org.whispersystems.textsecuregcm.proto.GroupChange.getDefaultInstance() : groupChange_;
    }
    /**
     * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
     */
    @Override
    public org.whispersystems.textsecuregcm.proto.GroupChangeOrBuilder getGroupChangeOrBuilder() {
      return getGroupChange();
    }

    public static final int GROUPSTATE_FIELD_NUMBER = 2;
    private org.whispersystems.textsecuregcm.proto.Group groupState_;
    /**
     * <code>.GroupsProtos.Group groupState = 2;</code>
     * @return Whether the groupState field is set.
     */
    @Override
    public boolean hasGroupState() {
      return groupState_ != null;
    }
    /**
     * <code>.GroupsProtos.Group groupState = 2;</code>
     * @return The groupState.
     */
    @Override
    public org.whispersystems.textsecuregcm.proto.Group getGroupState() {
      return groupState_ == null ? org.whispersystems.textsecuregcm.proto.Group.getDefaultInstance() : groupState_;
    }
    /**
     * <code>.GroupsProtos.Group groupState = 2;</code>
     */
    @Override
    public org.whispersystems.textsecuregcm.proto.GroupOrBuilder getGroupStateOrBuilder() {
      return getGroupState();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (groupChange_ != null) {
        output.writeMessage(1, getGroupChange());
      }
      if (groupState_ != null) {
        output.writeMessage(2, getGroupState());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (groupChange_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGroupChange());
      }
      if (groupState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGroupState());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState)) {
        return super.equals(obj);
      }
      org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState other = (org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState) obj;

      if (hasGroupChange() != other.hasGroupChange()) return false;
      if (hasGroupChange()) {
        if (!getGroupChange()
            .equals(other.getGroupChange())) return false;
      }
      if (hasGroupState() != other.hasGroupState()) return false;
      if (hasGroupState()) {
        if (!getGroupState()
            .equals(other.getGroupState())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGroupChange()) {
        hash = (37 * hash) + GROUPCHANGE_FIELD_NUMBER;
        hash = (53 * hash) + getGroupChange().hashCode();
      }
      if (hasGroupState()) {
        hash = (37 * hash) + GROUPSTATE_FIELD_NUMBER;
        hash = (53 * hash) + getGroupState().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GroupsProtos.GroupChanges.GroupChangeState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GroupsProtos.GroupChanges.GroupChangeState)
        org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_GroupChangeState_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_GroupChangeState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.class, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder.class);
      }

      // Construct using org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (groupChangeBuilder_ == null) {
          groupChange_ = null;
        } else {
          groupChange_ = null;
          groupChangeBuilder_ = null;
        }
        if (groupStateBuilder_ == null) {
          groupState_ = null;
        } else {
          groupState_ = null;
          groupStateBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_GroupChangeState_descriptor;
      }

      @Override
      public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState getDefaultInstanceForType() {
        return org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.getDefaultInstance();
      }

      @Override
      public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState build() {
        org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState buildPartial() {
        org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState result = new org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState(this);
        if (groupChangeBuilder_ == null) {
          result.groupChange_ = groupChange_;
        } else {
          result.groupChange_ = groupChangeBuilder_.build();
        }
        if (groupStateBuilder_ == null) {
          result.groupState_ = groupState_;
        } else {
          result.groupState_ = groupStateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState) {
          return mergeFrom((org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState other) {
        if (other == org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.getDefaultInstance()) return this;
        if (other.hasGroupChange()) {
          mergeGroupChange(other.getGroupChange());
        }
        if (other.hasGroupState()) {
          mergeGroupState(other.getGroupState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.whispersystems.textsecuregcm.proto.GroupChange groupChange_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.proto.GroupChange, org.whispersystems.textsecuregcm.proto.GroupChange.Builder, org.whispersystems.textsecuregcm.proto.GroupChangeOrBuilder> groupChangeBuilder_;
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       * @return Whether the groupChange field is set.
       */
      public boolean hasGroupChange() {
        return groupChangeBuilder_ != null || groupChange_ != null;
      }
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       * @return The groupChange.
       */
      public org.whispersystems.textsecuregcm.proto.GroupChange getGroupChange() {
        if (groupChangeBuilder_ == null) {
          return groupChange_ == null ? org.whispersystems.textsecuregcm.proto.GroupChange.getDefaultInstance() : groupChange_;
        } else {
          return groupChangeBuilder_.getMessage();
        }
      }
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       */
      public Builder setGroupChange(org.whispersystems.textsecuregcm.proto.GroupChange value) {
        if (groupChangeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          groupChange_ = value;
          onChanged();
        } else {
          groupChangeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       */
      public Builder setGroupChange(
          org.whispersystems.textsecuregcm.proto.GroupChange.Builder builderForValue) {
        if (groupChangeBuilder_ == null) {
          groupChange_ = builderForValue.build();
          onChanged();
        } else {
          groupChangeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       */
      public Builder mergeGroupChange(org.whispersystems.textsecuregcm.proto.GroupChange value) {
        if (groupChangeBuilder_ == null) {
          if (groupChange_ != null) {
            groupChange_ =
              org.whispersystems.textsecuregcm.proto.GroupChange.newBuilder(groupChange_).mergeFrom(value).buildPartial();
          } else {
            groupChange_ = value;
          }
          onChanged();
        } else {
          groupChangeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       */
      public Builder clearGroupChange() {
        if (groupChangeBuilder_ == null) {
          groupChange_ = null;
          onChanged();
        } else {
          groupChange_ = null;
          groupChangeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       */
      public org.whispersystems.textsecuregcm.proto.GroupChange.Builder getGroupChangeBuilder() {
        
        onChanged();
        return getGroupChangeFieldBuilder().getBuilder();
      }
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       */
      public org.whispersystems.textsecuregcm.proto.GroupChangeOrBuilder getGroupChangeOrBuilder() {
        if (groupChangeBuilder_ != null) {
          return groupChangeBuilder_.getMessageOrBuilder();
        } else {
          return groupChange_ == null ?
              org.whispersystems.textsecuregcm.proto.GroupChange.getDefaultInstance() : groupChange_;
        }
      }
      /**
       * <code>.GroupsProtos.GroupChange groupChange = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.proto.GroupChange, org.whispersystems.textsecuregcm.proto.GroupChange.Builder, org.whispersystems.textsecuregcm.proto.GroupChangeOrBuilder>
          getGroupChangeFieldBuilder() {
        if (groupChangeBuilder_ == null) {
          groupChangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.whispersystems.textsecuregcm.proto.GroupChange, org.whispersystems.textsecuregcm.proto.GroupChange.Builder, org.whispersystems.textsecuregcm.proto.GroupChangeOrBuilder>(
                  getGroupChange(),
                  getParentForChildren(),
                  isClean());
          groupChange_ = null;
        }
        return groupChangeBuilder_;
      }

      private org.whispersystems.textsecuregcm.proto.Group groupState_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.proto.Group, org.whispersystems.textsecuregcm.proto.Group.Builder, org.whispersystems.textsecuregcm.proto.GroupOrBuilder> groupStateBuilder_;
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       * @return Whether the groupState field is set.
       */
      public boolean hasGroupState() {
        return groupStateBuilder_ != null || groupState_ != null;
      }
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       * @return The groupState.
       */
      public org.whispersystems.textsecuregcm.proto.Group getGroupState() {
        if (groupStateBuilder_ == null) {
          return groupState_ == null ? org.whispersystems.textsecuregcm.proto.Group.getDefaultInstance() : groupState_;
        } else {
          return groupStateBuilder_.getMessage();
        }
      }
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       */
      public Builder setGroupState(org.whispersystems.textsecuregcm.proto.Group value) {
        if (groupStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          groupState_ = value;
          onChanged();
        } else {
          groupStateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       */
      public Builder setGroupState(
          org.whispersystems.textsecuregcm.proto.Group.Builder builderForValue) {
        if (groupStateBuilder_ == null) {
          groupState_ = builderForValue.build();
          onChanged();
        } else {
          groupStateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       */
      public Builder mergeGroupState(org.whispersystems.textsecuregcm.proto.Group value) {
        if (groupStateBuilder_ == null) {
          if (groupState_ != null) {
            groupState_ =
              org.whispersystems.textsecuregcm.proto.Group.newBuilder(groupState_).mergeFrom(value).buildPartial();
          } else {
            groupState_ = value;
          }
          onChanged();
        } else {
          groupStateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       */
      public Builder clearGroupState() {
        if (groupStateBuilder_ == null) {
          groupState_ = null;
          onChanged();
        } else {
          groupState_ = null;
          groupStateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       */
      public org.whispersystems.textsecuregcm.proto.Group.Builder getGroupStateBuilder() {
        
        onChanged();
        return getGroupStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       */
      public org.whispersystems.textsecuregcm.proto.GroupOrBuilder getGroupStateOrBuilder() {
        if (groupStateBuilder_ != null) {
          return groupStateBuilder_.getMessageOrBuilder();
        } else {
          return groupState_ == null ?
              org.whispersystems.textsecuregcm.proto.Group.getDefaultInstance() : groupState_;
        }
      }
      /**
       * <code>.GroupsProtos.Group groupState = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.proto.Group, org.whispersystems.textsecuregcm.proto.Group.Builder, org.whispersystems.textsecuregcm.proto.GroupOrBuilder>
          getGroupStateFieldBuilder() {
        if (groupStateBuilder_ == null) {
          groupStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.whispersystems.textsecuregcm.proto.Group, org.whispersystems.textsecuregcm.proto.Group.Builder, org.whispersystems.textsecuregcm.proto.GroupOrBuilder>(
                  getGroupState(),
                  getParentForChildren(),
                  isClean());
          groupState_ = null;
        }
        return groupStateBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GroupsProtos.GroupChanges.GroupChangeState)
    }

    // @@protoc_insertion_point(class_scope:GroupsProtos.GroupChanges.GroupChangeState)
    private static final org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState();
    }

    public static org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupChangeState>
        PARSER = new com.google.protobuf.AbstractParser<GroupChangeState>() {
      @Override
      public GroupChangeState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupChangeState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupChangeState> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GroupChangeState> getParserForType() {
      return PARSER;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int GROUPCHANGES_FIELD_NUMBER = 1;
  private java.util.List<org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState> groupChanges_;
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  @Override
  public java.util.List<org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState> getGroupChangesList() {
    return groupChanges_;
  }
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  @Override
  public java.util.List<? extends org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder>
      getGroupChangesOrBuilderList() {
    return groupChanges_;
  }
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  @Override
  public int getGroupChangesCount() {
    return groupChanges_.size();
  }
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState getGroupChanges(int index) {
    return groupChanges_.get(index);
  }
  /**
   * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder getGroupChangesOrBuilder(
      int index) {
    return groupChanges_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < groupChanges_.size(); i++) {
      output.writeMessage(1, groupChanges_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < groupChanges_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, groupChanges_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.whispersystems.textsecuregcm.proto.GroupChanges)) {
      return super.equals(obj);
    }
    org.whispersystems.textsecuregcm.proto.GroupChanges other = (org.whispersystems.textsecuregcm.proto.GroupChanges) obj;

    if (!getGroupChangesList()
        .equals(other.getGroupChangesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGroupChangesCount() > 0) {
      hash = (37 * hash) + GROUPCHANGES_FIELD_NUMBER;
      hash = (53 * hash) + getGroupChangesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupChanges parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.whispersystems.textsecuregcm.proto.GroupChanges prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GroupsProtos.GroupChanges}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GroupsProtos.GroupChanges)
      org.whispersystems.textsecuregcm.proto.GroupChangesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.proto.GroupChanges.class, org.whispersystems.textsecuregcm.proto.GroupChanges.Builder.class);
    }

    // Construct using org.whispersystems.textsecuregcm.proto.GroupChanges.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGroupChangesFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (groupChangesBuilder_ == null) {
        groupChanges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        groupChangesBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupChanges_descriptor;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.GroupChanges getDefaultInstanceForType() {
      return org.whispersystems.textsecuregcm.proto.GroupChanges.getDefaultInstance();
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.GroupChanges build() {
      org.whispersystems.textsecuregcm.proto.GroupChanges result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.GroupChanges buildPartial() {
      org.whispersystems.textsecuregcm.proto.GroupChanges result = new org.whispersystems.textsecuregcm.proto.GroupChanges(this);
      int from_bitField0_ = bitField0_;
      if (groupChangesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          groupChanges_ = java.util.Collections.unmodifiableList(groupChanges_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.groupChanges_ = groupChanges_;
      } else {
        result.groupChanges_ = groupChangesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.whispersystems.textsecuregcm.proto.GroupChanges) {
        return mergeFrom((org.whispersystems.textsecuregcm.proto.GroupChanges)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.whispersystems.textsecuregcm.proto.GroupChanges other) {
      if (other == org.whispersystems.textsecuregcm.proto.GroupChanges.getDefaultInstance()) return this;
      if (groupChangesBuilder_ == null) {
        if (!other.groupChanges_.isEmpty()) {
          if (groupChanges_.isEmpty()) {
            groupChanges_ = other.groupChanges_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGroupChangesIsMutable();
            groupChanges_.addAll(other.groupChanges_);
          }
          onChanged();
        }
      } else {
        if (!other.groupChanges_.isEmpty()) {
          if (groupChangesBuilder_.isEmpty()) {
            groupChangesBuilder_.dispose();
            groupChangesBuilder_ = null;
            groupChanges_ = other.groupChanges_;
            bitField0_ = (bitField0_ & ~0x00000001);
            groupChangesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGroupChangesFieldBuilder() : null;
          } else {
            groupChangesBuilder_.addAllMessages(other.groupChanges_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.whispersystems.textsecuregcm.proto.GroupChanges parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.whispersystems.textsecuregcm.proto.GroupChanges) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState> groupChanges_ =
      java.util.Collections.emptyList();
    private void ensureGroupChangesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        groupChanges_ = new java.util.ArrayList<org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState>(groupChanges_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder> groupChangesBuilder_;

    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public java.util.List<org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState> getGroupChangesList() {
      if (groupChangesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(groupChanges_);
      } else {
        return groupChangesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public int getGroupChangesCount() {
      if (groupChangesBuilder_ == null) {
        return groupChanges_.size();
      } else {
        return groupChangesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState getGroupChanges(int index) {
      if (groupChangesBuilder_ == null) {
        return groupChanges_.get(index);
      } else {
        return groupChangesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder setGroupChanges(
        int index, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState value) {
      if (groupChangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupChangesIsMutable();
        groupChanges_.set(index, value);
        onChanged();
      } else {
        groupChangesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder setGroupChanges(
        int index, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder builderForValue) {
      if (groupChangesBuilder_ == null) {
        ensureGroupChangesIsMutable();
        groupChanges_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupChangesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder addGroupChanges(org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState value) {
      if (groupChangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupChangesIsMutable();
        groupChanges_.add(value);
        onChanged();
      } else {
        groupChangesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder addGroupChanges(
        int index, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState value) {
      if (groupChangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupChangesIsMutable();
        groupChanges_.add(index, value);
        onChanged();
      } else {
        groupChangesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder addGroupChanges(
        org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder builderForValue) {
      if (groupChangesBuilder_ == null) {
        ensureGroupChangesIsMutable();
        groupChanges_.add(builderForValue.build());
        onChanged();
      } else {
        groupChangesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder addGroupChanges(
        int index, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder builderForValue) {
      if (groupChangesBuilder_ == null) {
        ensureGroupChangesIsMutable();
        groupChanges_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupChangesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder addAllGroupChanges(
        Iterable<? extends org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState> values) {
      if (groupChangesBuilder_ == null) {
        ensureGroupChangesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupChanges_);
        onChanged();
      } else {
        groupChangesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder clearGroupChanges() {
      if (groupChangesBuilder_ == null) {
        groupChanges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        groupChangesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public Builder removeGroupChanges(int index) {
      if (groupChangesBuilder_ == null) {
        ensureGroupChangesIsMutable();
        groupChanges_.remove(index);
        onChanged();
      } else {
        groupChangesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder getGroupChangesBuilder(
        int index) {
      return getGroupChangesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder getGroupChangesOrBuilder(
        int index) {
      if (groupChangesBuilder_ == null) {
        return groupChanges_.get(index);  } else {
        return groupChangesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public java.util.List<? extends org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder>
         getGroupChangesOrBuilderList() {
      if (groupChangesBuilder_ != null) {
        return groupChangesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(groupChanges_);
      }
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder addGroupChangesBuilder() {
      return getGroupChangesFieldBuilder().addBuilder(
          org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.getDefaultInstance());
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder addGroupChangesBuilder(
        int index) {
      return getGroupChangesFieldBuilder().addBuilder(
          index, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.getDefaultInstance());
    }
    /**
     * <code>repeated .GroupsProtos.GroupChanges.GroupChangeState groupChanges = 1;</code>
     */
    public java.util.List<org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder>
         getGroupChangesBuilderList() {
      return getGroupChangesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder>
        getGroupChangesFieldBuilder() {
      if (groupChangesBuilder_ == null) {
        groupChangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeState.Builder, org.whispersystems.textsecuregcm.proto.GroupChanges.GroupChangeStateOrBuilder>(
                groupChanges_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        groupChanges_ = null;
      }
      return groupChangesBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GroupsProtos.GroupChanges)
  }

  // @@protoc_insertion_point(class_scope:GroupsProtos.GroupChanges)
  private static final org.whispersystems.textsecuregcm.proto.GroupChanges DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.proto.GroupChanges();
  }

  public static org.whispersystems.textsecuregcm.proto.GroupChanges getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupChanges>
      PARSER = new com.google.protobuf.AbstractParser<GroupChanges>() {
    @Override
    public GroupChanges parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GroupChanges(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GroupChanges> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GroupChanges> getParserForType() {
    return PARSER;
  }

  @Override
  public org.whispersystems.textsecuregcm.proto.GroupChanges getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

