// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

/**
 * Protobuf type {@code GroupsProtos.GroupAttributeBlob}
 */
public final class GroupAttributeBlob extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GroupsProtos.GroupAttributeBlob)
    GroupAttributeBlobOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GroupAttributeBlob.newBuilder() to construct.
  private GroupAttributeBlob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupAttributeBlob() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GroupAttributeBlob();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GroupAttributeBlob(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            contentCase_ = 1;
            content_ = s;
            break;
          }
          case 18: {
            contentCase_ = 2;
            content_ = input.readBytes();
            break;
          }
          case 24: {
            contentCase_ = 3;
            content_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupAttributeBlob_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupAttributeBlob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.whispersystems.textsecuregcm.proto.GroupAttributeBlob.class, org.whispersystems.textsecuregcm.proto.GroupAttributeBlob.Builder.class);
  }

  private int contentCase_ = 0;
  private Object content_;
  public enum ContentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TITLE(1),
    AVATAR(2),
    DISAPPEARINGMESSAGESDURATION(3),
    CONTENT_NOT_SET(0);
    private final int value;
    private ContentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ContentCase valueOf(int value) {
      return forNumber(value);
    }

    public static ContentCase forNumber(int value) {
      switch (value) {
        case 1: return TITLE;
        case 2: return AVATAR;
        case 3: return DISAPPEARINGMESSAGESDURATION;
        case 0: return CONTENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ContentCase
  getContentCase() {
    return ContentCase.forNumber(
        contentCase_);
  }

  public static final int TITLE_FIELD_NUMBER = 1;
  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  public String getTitle() {
    Object ref = "";
    if (contentCase_ == 1) {
      ref = content_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (contentCase_ == 1) {
        content_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    Object ref = "";
    if (contentCase_ == 1) {
      ref = content_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (contentCase_ == 1) {
        content_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATAR_FIELD_NUMBER = 2;
  /**
   * <code>bytes avatar = 2;</code>
   * @return The avatar.
   */
  @Override
  public com.google.protobuf.ByteString getAvatar() {
    if (contentCase_ == 2) {
      return (com.google.protobuf.ByteString) content_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int DISAPPEARINGMESSAGESDURATION_FIELD_NUMBER = 3;
  /**
   * <code>uint32 disappearingMessagesDuration = 3;</code>
   * @return The disappearingMessagesDuration.
   */
  @Override
  public int getDisappearingMessagesDuration() {
    if (contentCase_ == 3) {
      return (Integer) content_;
    }
    return 0;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (contentCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
    }
    if (contentCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) content_);
    }
    if (contentCase_ == 3) {
      output.writeUInt32(
          3, (int)((Integer) content_));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (contentCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
    }
    if (contentCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) content_);
    }
    if (contentCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(
            3, (int)((Integer) content_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.whispersystems.textsecuregcm.proto.GroupAttributeBlob)) {
      return super.equals(obj);
    }
    org.whispersystems.textsecuregcm.proto.GroupAttributeBlob other = (org.whispersystems.textsecuregcm.proto.GroupAttributeBlob) obj;

    if (!getContentCase().equals(other.getContentCase())) return false;
    switch (contentCase_) {
      case 1:
        if (!getTitle()
            .equals(other.getTitle())) return false;
        break;
      case 2:
        if (!getAvatar()
            .equals(other.getAvatar())) return false;
        break;
      case 3:
        if (getDisappearingMessagesDuration()
            != other.getDisappearingMessagesDuration()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (contentCase_) {
      case 1:
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
        break;
      case 2:
        hash = (37 * hash) + AVATAR_FIELD_NUMBER;
        hash = (53 * hash) + getAvatar().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DISAPPEARINGMESSAGESDURATION_FIELD_NUMBER;
        hash = (53 * hash) + getDisappearingMessagesDuration();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.whispersystems.textsecuregcm.proto.GroupAttributeBlob prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GroupsProtos.GroupAttributeBlob}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GroupsProtos.GroupAttributeBlob)
      org.whispersystems.textsecuregcm.proto.GroupAttributeBlobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupAttributeBlob_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupAttributeBlob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.proto.GroupAttributeBlob.class, org.whispersystems.textsecuregcm.proto.GroupAttributeBlob.Builder.class);
    }

    // Construct using org.whispersystems.textsecuregcm.proto.GroupAttributeBlob.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      contentCase_ = 0;
      content_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_GroupAttributeBlob_descriptor;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.GroupAttributeBlob getDefaultInstanceForType() {
      return org.whispersystems.textsecuregcm.proto.GroupAttributeBlob.getDefaultInstance();
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.GroupAttributeBlob build() {
      org.whispersystems.textsecuregcm.proto.GroupAttributeBlob result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.GroupAttributeBlob buildPartial() {
      org.whispersystems.textsecuregcm.proto.GroupAttributeBlob result = new org.whispersystems.textsecuregcm.proto.GroupAttributeBlob(this);
      if (contentCase_ == 1) {
        result.content_ = content_;
      }
      if (contentCase_ == 2) {
        result.content_ = content_;
      }
      if (contentCase_ == 3) {
        result.content_ = content_;
      }
      result.contentCase_ = contentCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.whispersystems.textsecuregcm.proto.GroupAttributeBlob) {
        return mergeFrom((org.whispersystems.textsecuregcm.proto.GroupAttributeBlob)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.whispersystems.textsecuregcm.proto.GroupAttributeBlob other) {
      if (other == org.whispersystems.textsecuregcm.proto.GroupAttributeBlob.getDefaultInstance()) return this;
      switch (other.getContentCase()) {
        case TITLE: {
          contentCase_ = 1;
          content_ = other.content_;
          onChanged();
          break;
        }
        case AVATAR: {
          setAvatar(other.getAvatar());
          break;
        }
        case DISAPPEARINGMESSAGESDURATION: {
          setDisappearingMessagesDuration(other.getDisappearingMessagesDuration());
          break;
        }
        case CONTENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.whispersystems.textsecuregcm.proto.GroupAttributeBlob parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.whispersystems.textsecuregcm.proto.GroupAttributeBlob) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int contentCase_ = 0;
    private Object content_;
    public ContentCase
        getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public Builder clearContent() {
      contentCase_ = 0;
      content_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @Override
    public String getTitle() {
      Object ref = "";
      if (contentCase_ == 1) {
        ref = content_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (contentCase_ == 1) {
          content_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = "";
      if (contentCase_ == 1) {
        ref = content_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (contentCase_ == 1) {
          content_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  contentCase_ = 1;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      if (contentCase_ == 1) {
        contentCase_ = 0;
        content_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      contentCase_ = 1;
      content_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bytes avatar = 2;</code>
     * @return The avatar.
     */
    public com.google.protobuf.ByteString getAvatar() {
      if (contentCase_ == 2) {
        return (com.google.protobuf.ByteString) content_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes avatar = 2;</code>
     * @param value The avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatar(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  contentCase_ = 2;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes avatar = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatar() {
      if (contentCase_ == 2) {
        contentCase_ = 0;
        content_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>uint32 disappearingMessagesDuration = 3;</code>
     * @return The disappearingMessagesDuration.
     */
    public int getDisappearingMessagesDuration() {
      if (contentCase_ == 3) {
        return (Integer) content_;
      }
      return 0;
    }
    /**
     * <code>uint32 disappearingMessagesDuration = 3;</code>
     * @param value The disappearingMessagesDuration to set.
     * @return This builder for chaining.
     */
    public Builder setDisappearingMessagesDuration(int value) {
      contentCase_ = 3;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 disappearingMessagesDuration = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisappearingMessagesDuration() {
      if (contentCase_ == 3) {
        contentCase_ = 0;
        content_ = null;
        onChanged();
      }
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GroupsProtos.GroupAttributeBlob)
  }

  // @@protoc_insertion_point(class_scope:GroupsProtos.GroupAttributeBlob)
  private static final org.whispersystems.textsecuregcm.proto.GroupAttributeBlob DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.proto.GroupAttributeBlob();
  }

  public static org.whispersystems.textsecuregcm.proto.GroupAttributeBlob getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupAttributeBlob>
      PARSER = new com.google.protobuf.AbstractParser<GroupAttributeBlob>() {
    @Override
    public GroupAttributeBlob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GroupAttributeBlob(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GroupAttributeBlob> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GroupAttributeBlob> getParserForType() {
    return PARSER;
  }

  @Override
  public org.whispersystems.textsecuregcm.proto.GroupAttributeBlob getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

