// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

public final class Groups {
  private Groups() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_AvatarUploadAttributes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_AvatarUploadAttributes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_Member_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_Member_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_PendingMember_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_PendingMember_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_AccessControl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_AccessControl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_AddMemberAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_AddMemberAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_DeleteMemberAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_DeleteMemberAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberRoleAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberRoleAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberProfileKeyAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberProfileKeyAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_AddPendingMemberAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_AddPendingMemberAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_DeletePendingMemberAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_DeletePendingMemberAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_PromotePendingMemberAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_PromotePendingMemberAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_ModifyTitleAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_ModifyTitleAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_ModifyDisappearingMessagesTimerAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_ModifyDisappearingMessagesTimerAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAttributesAccessControlAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_ModifyAttributesAccessControlAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAccessControlAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAccessControlAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMembersAccessControlAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChange_Actions_ModifyMembersAccessControlAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChanges_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChanges_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupChanges_GroupChangeState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupChanges_GroupChangeState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsProtos_GroupAttributeBlob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsProtos_GroupAttributeBlob_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Groups.proto\022\014GroupsProtos\"\212\001\n\026AvatarU" +
      "ploadAttributes\022\013\n\003key\030\001 \001(\t\022\022\n\ncredenti" +
      "al\030\002 \001(\t\022\013\n\003acl\030\003 \001(\t\022\021\n\talgorithm\030\004 \001(\t" +
      "\022\014\n\004date\030\005 \001(\t\022\016\n\006policy\030\006 \001(\t\022\021\n\tsignat" +
      "ure\030\007 \001(\t\"\272\001\n\006Member\022\016\n\006userId\030\001 \001(\014\022\'\n\004" +
      "role\030\002 \001(\0162\031.GroupsProtos.Member.Role\022\022\n" +
      "\nprofileKey\030\003 \001(\014\022\024\n\014presentation\030\004 \001(\014\022" +
      "\030\n\020joinedAtRevision\030\005 \001(\r\"3\n\004Role\022\013\n\007UNK" +
      "NOWN\020\000\022\013\n\007DEFAULT\020\001\022\021\n\rADMINISTRATOR\020\002\"_" +
      "\n\rPendingMember\022$\n\006member\030\001 \001(\0132\024.Groups" +
      "Protos.Member\022\025\n\raddedByUserId\030\002 \001(\014\022\021\n\t" +
      "timestamp\030\003 \001(\004\"\323\001\n\rAccessControl\022>\n\natt" +
      "ributes\030\001 \001(\0162*.GroupsProtos.AccessContr" +
      "ol.AccessRequired\022;\n\007members\030\002 \001(\0162*.Gro" +
      "upsProtos.AccessControl.AccessRequired\"E" +
      "\n\016AccessRequired\022\013\n\007UNKNOWN\020\000\022\007\n\003ANY\020\001\022\n" +
      "\n\006MEMBER\020\002\022\021\n\rADMINISTRATOR\020\003\"\376\001\n\005Group\022" +
      "\021\n\tpublicKey\030\001 \001(\014\022\r\n\005title\030\002 \001(\014\022\016\n\006ava" +
      "tar\030\003 \001(\t\022!\n\031disappearingMessagesTimer\030\004" +
      " \001(\014\0222\n\raccessControl\030\005 \001(\0132\033.GroupsProt" +
      "os.AccessControl\022\020\n\010revision\030\006 \001(\r\022%\n\007me" +
      "mbers\030\007 \003(\0132\024.GroupsProtos.Member\0223\n\016pen" +
      "dingMembers\030\010 \003(\0132\033.GroupsProtos.Pending" +
      "Member\"\373\017\n\013GroupChange\022\017\n\007actions\030\001 \001(\014\022" +
      "\027\n\017serverSignature\030\002 \001(\014\022\023\n\013changeEpoch\030" +
      "\003 \001(\r\032\254\017\n\007Actions\022\022\n\nsourceUuid\030\001 \001(\014\022\020\n" +
      "\010revision\030\002 \001(\r\022E\n\naddMembers\030\003 \003(\01321.Gr" +
      "oupsProtos.GroupChange.Actions.AddMember" +
      "Action\022K\n\rdeleteMembers\030\004 \003(\01324.GroupsPr" +
      "otos.GroupChange.Actions.DeleteMemberAct" +
      "ion\022S\n\021modifyMemberRoles\030\005 \003(\01328.GroupsP" +
      "rotos.GroupChange.Actions.ModifyMemberRo" +
      "leAction\022_\n\027modifyMemberProfileKeys\030\006 \003(" +
      "\0132>.GroupsProtos.GroupChange.Actions.Mod" +
      "ifyMemberProfileKeyAction\022S\n\021addPendingM" +
      "embers\030\007 \003(\01328.GroupsProtos.GroupChange." +
      "Actions.AddPendingMemberAction\022Y\n\024delete" +
      "PendingMembers\030\010 \003(\0132;.GroupsProtos.Grou" +
      "pChange.Actions.DeletePendingMemberActio" +
      "n\022[\n\025promotePendingMembers\030\t \003(\0132<.Group" +
      "sProtos.GroupChange.Actions.PromotePendi" +
      "ngMemberAction\022H\n\013modifyTitle\030\n \001(\01323.Gr" +
      "oupsProtos.GroupChange.Actions.ModifyTit" +
      "leAction\022J\n\014modifyAvatar\030\013 \001(\01324.GroupsP" +
      "rotos.GroupChange.Actions.ModifyAvatarAc" +
      "tion\022p\n\037modifyDisappearingMessagesTimer\030" +
      "\014 \001(\0132G.GroupsProtos.GroupChange.Actions" +
      ".ModifyDisappearingMessagesTimerAction\022e" +
      "\n\026modifyAttributesAccess\030\r \001(\0132E.GroupsP" +
      "rotos.GroupChange.Actions.ModifyAttribut" +
      "esAccessControlAction\022^\n\022modifyMemberAcc" +
      "ess\030\016 \001(\0132B.GroupsProtos.GroupChange.Act" +
      "ions.ModifyMembersAccessControlAction\0326\n" +
      "\017AddMemberAction\022#\n\005added\030\001 \001(\0132\024.Groups" +
      "Protos.Member\032+\n\022DeleteMemberAction\022\025\n\rd" +
      "eletedUserId\030\001 \001(\014\032Q\n\026ModifyMemberRoleAc" +
      "tion\022\016\n\006userId\030\001 \001(\014\022\'\n\004role\030\002 \001(\0162\031.Gro" +
      "upsProtos.Member.Role\0324\n\034ModifyMemberPro" +
      "fileKeyAction\022\024\n\014presentation\030\001 \001(\014\032D\n\026A" +
      "ddPendingMemberAction\022*\n\005added\030\001 \001(\0132\033.G" +
      "roupsProtos.PendingMember\0322\n\031DeletePendi" +
      "ngMemberAction\022\025\n\rdeletedUserId\030\001 \001(\014\0322\n" +
      "\032PromotePendingMemberAction\022\024\n\014presentat" +
      "ion\030\001 \001(\014\032\"\n\021ModifyTitleAction\022\r\n\005title\030" +
      "\001 \001(\014\032$\n\022ModifyAvatarAction\022\016\n\006avatar\030\001 " +
      "\001(\t\0326\n%ModifyDisappearingMessagesTimerAc" +
      "tion\022\r\n\005timer\030\001 \001(\014\032k\n#ModifyAttributesA" +
      "ccessControlAction\022D\n\020attributesAccess\030\001" +
      " \001(\0162*.GroupsProtos.AccessControl.Access" +
      "Required\032c\n\037ModifyAvatarAccessControlAct" +
      "ion\022@\n\014avatarAccess\030\001 \001(\0162*.GroupsProtos" +
      ".AccessControl.AccessRequired\032e\n ModifyM" +
      "embersAccessControlAction\022A\n\rmembersAcce" +
      "ss\030\001 \001(\0162*.GroupsProtos.AccessControl.Ac" +
      "cessRequired\"\276\001\n\014GroupChanges\022A\n\014groupCh" +
      "anges\030\001 \003(\0132+.GroupsProtos.GroupChanges." +
      "GroupChangeState\032k\n\020GroupChangeState\022.\n\013" +
      "groupChange\030\001 \001(\0132\031.GroupsProtos.GroupCh" +
      "ange\022\'\n\ngroupState\030\002 \001(\0132\023.GroupsProtos." +
      "Group\"j\n\022GroupAttributeBlob\022\017\n\005title\030\001 \001" +
      "(\tH\000\022\020\n\006avatar\030\002 \001(\014H\000\022&\n\034disappearingMe" +
      "ssagesDuration\030\003 \001(\rH\000B\t\n\007contentB+\n\'org" +
      ".signal.storageservice.protos.groupsP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GroupsProtos_AvatarUploadAttributes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GroupsProtos_AvatarUploadAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_AvatarUploadAttributes_descriptor,
        new String[] { "Key", "Credential", "Acl", "Algorithm", "Date", "Policy", "Signature", });
    internal_static_GroupsProtos_Member_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GroupsProtos_Member_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_Member_descriptor,
        new String[] { "UserId", "Role", "ProfileKey", "Presentation", "JoinedAtRevision", });
    internal_static_GroupsProtos_PendingMember_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GroupsProtos_PendingMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_PendingMember_descriptor,
        new String[] { "Member", "AddedByUserId", "Timestamp", });
    internal_static_GroupsProtos_AccessControl_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GroupsProtos_AccessControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_AccessControl_descriptor,
        new String[] { "Attributes", "Members", });
    internal_static_GroupsProtos_Group_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GroupsProtos_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_Group_descriptor,
        new String[] { "PublicKey", "Title", "Avatar", "DisappearingMessagesTimer", "AccessControl", "Revision", "Members", "PendingMembers", });
    internal_static_GroupsProtos_GroupChange_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GroupsProtos_GroupChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_descriptor,
        new String[] { "Actions", "ServerSignature", "ChangeEpoch", });
    internal_static_GroupsProtos_GroupChange_Actions_descriptor =
      internal_static_GroupsProtos_GroupChange_descriptor.getNestedTypes().get(0);
    internal_static_GroupsProtos_GroupChange_Actions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_descriptor,
        new String[] { "SourceUuid", "Revision", "AddMembers", "DeleteMembers", "ModifyMemberRoles", "ModifyMemberProfileKeys", "AddPendingMembers", "DeletePendingMembers", "PromotePendingMembers", "ModifyTitle", "ModifyAvatar", "ModifyDisappearingMessagesTimer", "ModifyAttributesAccess", "ModifyMemberAccess", });
    internal_static_GroupsProtos_GroupChange_Actions_AddMemberAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(0);
    internal_static_GroupsProtos_GroupChange_Actions_AddMemberAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_AddMemberAction_descriptor,
        new String[] { "Added", });
    internal_static_GroupsProtos_GroupChange_Actions_DeleteMemberAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(1);
    internal_static_GroupsProtos_GroupChange_Actions_DeleteMemberAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_DeleteMemberAction_descriptor,
        new String[] { "DeletedUserId", });
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberRoleAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(2);
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberRoleAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberRoleAction_descriptor,
        new String[] { "UserId", "Role", });
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberProfileKeyAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(3);
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberProfileKeyAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_ModifyMemberProfileKeyAction_descriptor,
        new String[] { "Presentation", });
    internal_static_GroupsProtos_GroupChange_Actions_AddPendingMemberAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(4);
    internal_static_GroupsProtos_GroupChange_Actions_AddPendingMemberAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_AddPendingMemberAction_descriptor,
        new String[] { "Added", });
    internal_static_GroupsProtos_GroupChange_Actions_DeletePendingMemberAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(5);
    internal_static_GroupsProtos_GroupChange_Actions_DeletePendingMemberAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_DeletePendingMemberAction_descriptor,
        new String[] { "DeletedUserId", });
    internal_static_GroupsProtos_GroupChange_Actions_PromotePendingMemberAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(6);
    internal_static_GroupsProtos_GroupChange_Actions_PromotePendingMemberAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_PromotePendingMemberAction_descriptor,
        new String[] { "Presentation", });
    internal_static_GroupsProtos_GroupChange_Actions_ModifyTitleAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(7);
    internal_static_GroupsProtos_GroupChange_Actions_ModifyTitleAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_ModifyTitleAction_descriptor,
        new String[] { "Title", });
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(8);
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAction_descriptor,
        new String[] { "Avatar", });
    internal_static_GroupsProtos_GroupChange_Actions_ModifyDisappearingMessagesTimerAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(9);
    internal_static_GroupsProtos_GroupChange_Actions_ModifyDisappearingMessagesTimerAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_ModifyDisappearingMessagesTimerAction_descriptor,
        new String[] { "Timer", });
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAttributesAccessControlAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(10);
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAttributesAccessControlAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_ModifyAttributesAccessControlAction_descriptor,
        new String[] { "AttributesAccess", });
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAccessControlAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(11);
    internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAccessControlAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_ModifyAvatarAccessControlAction_descriptor,
        new String[] { "AvatarAccess", });
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMembersAccessControlAction_descriptor =
      internal_static_GroupsProtos_GroupChange_Actions_descriptor.getNestedTypes().get(12);
    internal_static_GroupsProtos_GroupChange_Actions_ModifyMembersAccessControlAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChange_Actions_ModifyMembersAccessControlAction_descriptor,
        new String[] { "MembersAccess", });
    internal_static_GroupsProtos_GroupChanges_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GroupsProtos_GroupChanges_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChanges_descriptor,
        new String[] { "GroupChanges", });
    internal_static_GroupsProtos_GroupChanges_GroupChangeState_descriptor =
      internal_static_GroupsProtos_GroupChanges_descriptor.getNestedTypes().get(0);
    internal_static_GroupsProtos_GroupChanges_GroupChangeState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupChanges_GroupChangeState_descriptor,
        new String[] { "GroupChange", "GroupState", });
    internal_static_GroupsProtos_GroupAttributeBlob_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GroupsProtos_GroupAttributeBlob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsProtos_GroupAttributeBlob_descriptor,
        new String[] { "Title", "Avatar", "DisappearingMessagesDuration", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
