// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

/**
 * Protobuf type {@code GroupsProtos.Member}
 */
public final class Member extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GroupsProtos.Member)
    MemberOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Member.newBuilder() to construct.
  private Member(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Member() {
    userId_ = com.google.protobuf.ByteString.EMPTY;
    role_ = 0;
    profileKey_ = com.google.protobuf.ByteString.EMPTY;
    presentation_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Member();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Member(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            userId_ = input.readBytes();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            role_ = rawValue;
            break;
          }
          case 26: {

            profileKey_ = input.readBytes();
            break;
          }
          case 34: {

            presentation_ = input.readBytes();
            break;
          }
          case 40: {

            joinedAtRevision_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Member_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Member_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.whispersystems.textsecuregcm.proto.Member.class, org.whispersystems.textsecuregcm.proto.Member.Builder.class);
  }

  /**
   * Protobuf enum {@code GroupsProtos.Member.Role}
   */
  public enum Role
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * Normal member
     * </pre>
     *
     * <code>DEFAULT = 1;</code>
     */
    DEFAULT(1),
    /**
     * <pre>
     * Group admin
     * </pre>
     *
     * <code>ADMINISTRATOR = 2;</code>
     */
    ADMINISTRATOR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Normal member
     * </pre>
     *
     * <code>DEFAULT = 1;</code>
     */
    public static final int DEFAULT_VALUE = 1;
    /**
     * <pre>
     * Group admin
     * </pre>
     *
     * <code>ADMINISTRATOR = 2;</code>
     */
    public static final int ADMINISTRATOR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Role valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Role forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return DEFAULT;
        case 2: return ADMINISTRATOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Role>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Role> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Role>() {
            public Role findValueByNumber(int number) {
              return Role.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.Member.getDescriptor().getEnumTypes().get(0);
    }

    private static final Role[] VALUES = values();

    public static Role valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Role(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GroupsProtos.Member.Role)
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString userId_;
  /**
   * <pre>
   * The UuidCiphertext
   * </pre>
   *
   * <code>bytes userId = 1;</code>
   * @return The userId.
   */
  @Override
  public com.google.protobuf.ByteString getUserId() {
    return userId_;
  }

  public static final int ROLE_FIELD_NUMBER = 2;
  private int role_;
  /**
   * <code>.GroupsProtos.Member.Role role = 2;</code>
   * @return The enum numeric value on the wire for role.
   */
  @Override public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.GroupsProtos.Member.Role role = 2;</code>
   * @return The role.
   */
  @Override public org.whispersystems.textsecuregcm.proto.Member.Role getRole() {
    @SuppressWarnings("deprecation")
    org.whispersystems.textsecuregcm.proto.Member.Role result = org.whispersystems.textsecuregcm.proto.Member.Role.valueOf(role_);
    return result == null ? org.whispersystems.textsecuregcm.proto.Member.Role.UNRECOGNIZED : result;
  }

  public static final int PROFILEKEY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString profileKey_;
  /**
   * <pre>
   * The ProfileKeyCiphertext
   * </pre>
   *
   * <code>bytes profileKey = 3;</code>
   * @return The profileKey.
   */
  @Override
  public com.google.protobuf.ByteString getProfileKey() {
    return profileKey_;
  }

  public static final int PRESENTATION_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString presentation_;
  /**
   * <pre>
   * ProfileKeyCredentialPresentation
   * </pre>
   *
   * <code>bytes presentation = 4;</code>
   * @return The presentation.
   */
  @Override
  public com.google.protobuf.ByteString getPresentation() {
    return presentation_;
  }

  public static final int JOINEDATREVISION_FIELD_NUMBER = 5;
  private int joinedAtRevision_;
  /**
   * <pre>
   * The Group.revision this member joined at
   * </pre>
   *
   * <code>uint32 joinedAtRevision = 5;</code>
   * @return The joinedAtRevision.
   */
  @Override
  public int getJoinedAtRevision() {
    return joinedAtRevision_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!userId_.isEmpty()) {
      output.writeBytes(1, userId_);
    }
    if (role_ != org.whispersystems.textsecuregcm.proto.Member.Role.UNKNOWN.getNumber()) {
      output.writeEnum(2, role_);
    }
    if (!profileKey_.isEmpty()) {
      output.writeBytes(3, profileKey_);
    }
    if (!presentation_.isEmpty()) {
      output.writeBytes(4, presentation_);
    }
    if (joinedAtRevision_ != 0) {
      output.writeUInt32(5, joinedAtRevision_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!userId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, userId_);
    }
    if (role_ != org.whispersystems.textsecuregcm.proto.Member.Role.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, role_);
    }
    if (!profileKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, profileKey_);
    }
    if (!presentation_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, presentation_);
    }
    if (joinedAtRevision_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, joinedAtRevision_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.whispersystems.textsecuregcm.proto.Member)) {
      return super.equals(obj);
    }
    org.whispersystems.textsecuregcm.proto.Member other = (org.whispersystems.textsecuregcm.proto.Member) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (role_ != other.role_) return false;
    if (!getProfileKey()
        .equals(other.getProfileKey())) return false;
    if (!getPresentation()
        .equals(other.getPresentation())) return false;
    if (getJoinedAtRevision()
        != other.getJoinedAtRevision()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + role_;
    hash = (37 * hash) + PROFILEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getProfileKey().hashCode();
    hash = (37 * hash) + PRESENTATION_FIELD_NUMBER;
    hash = (53 * hash) + getPresentation().hashCode();
    hash = (37 * hash) + JOINEDATREVISION_FIELD_NUMBER;
    hash = (53 * hash) + getJoinedAtRevision();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.Member parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.whispersystems.textsecuregcm.proto.Member prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GroupsProtos.Member}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GroupsProtos.Member)
      org.whispersystems.textsecuregcm.proto.MemberOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Member_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Member_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.proto.Member.class, org.whispersystems.textsecuregcm.proto.Member.Builder.class);
    }

    // Construct using org.whispersystems.textsecuregcm.proto.Member.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      userId_ = com.google.protobuf.ByteString.EMPTY;

      role_ = 0;

      profileKey_ = com.google.protobuf.ByteString.EMPTY;

      presentation_ = com.google.protobuf.ByteString.EMPTY;

      joinedAtRevision_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_Member_descriptor;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.Member getDefaultInstanceForType() {
      return org.whispersystems.textsecuregcm.proto.Member.getDefaultInstance();
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.Member build() {
      org.whispersystems.textsecuregcm.proto.Member result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.Member buildPartial() {
      org.whispersystems.textsecuregcm.proto.Member result = new org.whispersystems.textsecuregcm.proto.Member(this);
      result.userId_ = userId_;
      result.role_ = role_;
      result.profileKey_ = profileKey_;
      result.presentation_ = presentation_;
      result.joinedAtRevision_ = joinedAtRevision_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.whispersystems.textsecuregcm.proto.Member) {
        return mergeFrom((org.whispersystems.textsecuregcm.proto.Member)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.whispersystems.textsecuregcm.proto.Member other) {
      if (other == org.whispersystems.textsecuregcm.proto.Member.getDefaultInstance()) return this;
      if (other.getUserId() != com.google.protobuf.ByteString.EMPTY) {
        setUserId(other.getUserId());
      }
      if (other.role_ != 0) {
        setRoleValue(other.getRoleValue());
      }
      if (other.getProfileKey() != com.google.protobuf.ByteString.EMPTY) {
        setProfileKey(other.getProfileKey());
      }
      if (other.getPresentation() != com.google.protobuf.ByteString.EMPTY) {
        setPresentation(other.getPresentation());
      }
      if (other.getJoinedAtRevision() != 0) {
        setJoinedAtRevision(other.getJoinedAtRevision());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.whispersystems.textsecuregcm.proto.Member parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.whispersystems.textsecuregcm.proto.Member) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString userId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The UuidCiphertext
     * </pre>
     *
     * <code>bytes userId = 1;</code>
     * @return The userId.
     */
    @Override
    public com.google.protobuf.ByteString getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * The UuidCiphertext
     * </pre>
     *
     * <code>bytes userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The UuidCiphertext
     * </pre>
     *
     * <code>bytes userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }

    private int role_ = 0;
    /**
     * <code>.GroupsProtos.Member.Role role = 2;</code>
     * @return The enum numeric value on the wire for role.
     */
    @Override public int getRoleValue() {
      return role_;
    }
    /**
     * <code>.GroupsProtos.Member.Role role = 2;</code>
     * @param value The enum numeric value on the wire for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleValue(int value) {
      
      role_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.GroupsProtos.Member.Role role = 2;</code>
     * @return The role.
     */
    @Override
    public org.whispersystems.textsecuregcm.proto.Member.Role getRole() {
      @SuppressWarnings("deprecation")
      org.whispersystems.textsecuregcm.proto.Member.Role result = org.whispersystems.textsecuregcm.proto.Member.Role.valueOf(role_);
      return result == null ? org.whispersystems.textsecuregcm.proto.Member.Role.UNRECOGNIZED : result;
    }
    /**
     * <code>.GroupsProtos.Member.Role role = 2;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(org.whispersystems.textsecuregcm.proto.Member.Role value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      role_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GroupsProtos.Member.Role role = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      
      role_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString profileKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The ProfileKeyCiphertext
     * </pre>
     *
     * <code>bytes profileKey = 3;</code>
     * @return The profileKey.
     */
    @Override
    public com.google.protobuf.ByteString getProfileKey() {
      return profileKey_;
    }
    /**
     * <pre>
     * The ProfileKeyCiphertext
     * </pre>
     *
     * <code>bytes profileKey = 3;</code>
     * @param value The profileKey to set.
     * @return This builder for chaining.
     */
    public Builder setProfileKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      profileKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ProfileKeyCiphertext
     * </pre>
     *
     * <code>bytes profileKey = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfileKey() {
      
      profileKey_ = getDefaultInstance().getProfileKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString presentation_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * ProfileKeyCredentialPresentation
     * </pre>
     *
     * <code>bytes presentation = 4;</code>
     * @return The presentation.
     */
    @Override
    public com.google.protobuf.ByteString getPresentation() {
      return presentation_;
    }
    /**
     * <pre>
     * ProfileKeyCredentialPresentation
     * </pre>
     *
     * <code>bytes presentation = 4;</code>
     * @param value The presentation to set.
     * @return This builder for chaining.
     */
    public Builder setPresentation(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      presentation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ProfileKeyCredentialPresentation
     * </pre>
     *
     * <code>bytes presentation = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPresentation() {
      
      presentation_ = getDefaultInstance().getPresentation();
      onChanged();
      return this;
    }

    private int joinedAtRevision_ ;
    /**
     * <pre>
     * The Group.revision this member joined at
     * </pre>
     *
     * <code>uint32 joinedAtRevision = 5;</code>
     * @return The joinedAtRevision.
     */
    @Override
    public int getJoinedAtRevision() {
      return joinedAtRevision_;
    }
    /**
     * <pre>
     * The Group.revision this member joined at
     * </pre>
     *
     * <code>uint32 joinedAtRevision = 5;</code>
     * @param value The joinedAtRevision to set.
     * @return This builder for chaining.
     */
    public Builder setJoinedAtRevision(int value) {
      
      joinedAtRevision_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Group.revision this member joined at
     * </pre>
     *
     * <code>uint32 joinedAtRevision = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearJoinedAtRevision() {
      
      joinedAtRevision_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GroupsProtos.Member)
  }

  // @@protoc_insertion_point(class_scope:GroupsProtos.Member)
  private static final org.whispersystems.textsecuregcm.proto.Member DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.proto.Member();
  }

  public static org.whispersystems.textsecuregcm.proto.Member getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Member>
      PARSER = new com.google.protobuf.AbstractParser<Member>() {
    @Override
    public Member parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Member(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Member> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Member> getParserForType() {
    return PARSER;
  }

  @Override
  public org.whispersystems.textsecuregcm.proto.Member getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

