// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

public interface MemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupsProtos.Member)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The UuidCiphertext
   * </pre>
   *
   * <code>bytes userId = 1;</code>
   * @return The userId.
   */
  com.google.protobuf.ByteString getUserId();

  /**
   * <code>.GroupsProtos.Member.Role role = 2;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.GroupsProtos.Member.Role role = 2;</code>
   * @return The role.
   */
  org.whispersystems.textsecuregcm.proto.Member.Role getRole();

  /**
   * <pre>
   * The ProfileKeyCiphertext
   * </pre>
   *
   * <code>bytes profileKey = 3;</code>
   * @return The profileKey.
   */
  com.google.protobuf.ByteString getProfileKey();

  /**
   * <pre>
   * ProfileKeyCredentialPresentation
   * </pre>
   *
   * <code>bytes presentation = 4;</code>
   * @return The presentation.
   */
  com.google.protobuf.ByteString getPresentation();

  /**
   * <pre>
   * The Group.revision this member joined at
   * </pre>
   *
   * <code>uint32 joinedAtRevision = 5;</code>
   * @return The joinedAtRevision.
   */
  int getJoinedAtRevision();
}
