// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

/**
 * Protobuf type {@code GroupsProtos.PendingMember}
 */
public final class PendingMember extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GroupsProtos.PendingMember)
    PendingMemberOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PendingMember.newBuilder() to construct.
  private PendingMember(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PendingMember() {
    addedByUserId_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new PendingMember();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PendingMember(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.whispersystems.textsecuregcm.proto.Member.Builder subBuilder = null;
            if (member_ != null) {
              subBuilder = member_.toBuilder();
            }
            member_ = input.readMessage(org.whispersystems.textsecuregcm.proto.Member.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(member_);
              member_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {

            addedByUserId_ = input.readBytes();
            break;
          }
          case 24: {

            timestamp_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_PendingMember_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_PendingMember_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.whispersystems.textsecuregcm.proto.PendingMember.class, org.whispersystems.textsecuregcm.proto.PendingMember.Builder.class);
  }

  public static final int MEMBER_FIELD_NUMBER = 1;
  private org.whispersystems.textsecuregcm.proto.Member member_;
  /**
   * <pre>
   * The “invited” member
   * </pre>
   *
   * <code>.GroupsProtos.Member member = 1;</code>
   * @return Whether the member field is set.
   */
  @Override
  public boolean hasMember() {
    return member_ != null;
  }
  /**
   * <pre>
   * The “invited” member
   * </pre>
   *
   * <code>.GroupsProtos.Member member = 1;</code>
   * @return The member.
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.Member getMember() {
    return member_ == null ? org.whispersystems.textsecuregcm.proto.Member.getDefaultInstance() : member_;
  }
  /**
   * <pre>
   * The “invited” member
   * </pre>
   *
   * <code>.GroupsProtos.Member member = 1;</code>
   */
  @Override
  public org.whispersystems.textsecuregcm.proto.MemberOrBuilder getMemberOrBuilder() {
    return getMember();
  }

  public static final int ADDEDBYUSERID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString addedByUserId_;
  /**
   * <pre>
   * The UID who invited this member
   * </pre>
   *
   * <code>bytes addedByUserId = 2;</code>
   * @return The addedByUserId.
   */
  @Override
  public com.google.protobuf.ByteString getAddedByUserId() {
    return addedByUserId_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <pre>
   * The time the invitation occurred
   * </pre>
   *
   * <code>uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (member_ != null) {
      output.writeMessage(1, getMember());
    }
    if (!addedByUserId_.isEmpty()) {
      output.writeBytes(2, addedByUserId_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(3, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (member_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMember());
    }
    if (!addedByUserId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, addedByUserId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.whispersystems.textsecuregcm.proto.PendingMember)) {
      return super.equals(obj);
    }
    org.whispersystems.textsecuregcm.proto.PendingMember other = (org.whispersystems.textsecuregcm.proto.PendingMember) obj;

    if (hasMember() != other.hasMember()) return false;
    if (hasMember()) {
      if (!getMember()
          .equals(other.getMember())) return false;
    }
    if (!getAddedByUserId()
        .equals(other.getAddedByUserId())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMember()) {
      hash = (37 * hash) + MEMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMember().hashCode();
    }
    hash = (37 * hash) + ADDEDBYUSERID_FIELD_NUMBER;
    hash = (53 * hash) + getAddedByUserId().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.proto.PendingMember parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.whispersystems.textsecuregcm.proto.PendingMember prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GroupsProtos.PendingMember}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GroupsProtos.PendingMember)
      org.whispersystems.textsecuregcm.proto.PendingMemberOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_PendingMember_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_PendingMember_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.proto.PendingMember.class, org.whispersystems.textsecuregcm.proto.PendingMember.Builder.class);
    }

    // Construct using org.whispersystems.textsecuregcm.proto.PendingMember.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (memberBuilder_ == null) {
        member_ = null;
      } else {
        member_ = null;
        memberBuilder_ = null;
      }
      addedByUserId_ = com.google.protobuf.ByteString.EMPTY;

      timestamp_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.whispersystems.textsecuregcm.proto.Groups.internal_static_GroupsProtos_PendingMember_descriptor;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.PendingMember getDefaultInstanceForType() {
      return org.whispersystems.textsecuregcm.proto.PendingMember.getDefaultInstance();
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.PendingMember build() {
      org.whispersystems.textsecuregcm.proto.PendingMember result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.whispersystems.textsecuregcm.proto.PendingMember buildPartial() {
      org.whispersystems.textsecuregcm.proto.PendingMember result = new org.whispersystems.textsecuregcm.proto.PendingMember(this);
      if (memberBuilder_ == null) {
        result.member_ = member_;
      } else {
        result.member_ = memberBuilder_.build();
      }
      result.addedByUserId_ = addedByUserId_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.whispersystems.textsecuregcm.proto.PendingMember) {
        return mergeFrom((org.whispersystems.textsecuregcm.proto.PendingMember)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.whispersystems.textsecuregcm.proto.PendingMember other) {
      if (other == org.whispersystems.textsecuregcm.proto.PendingMember.getDefaultInstance()) return this;
      if (other.hasMember()) {
        mergeMember(other.getMember());
      }
      if (other.getAddedByUserId() != com.google.protobuf.ByteString.EMPTY) {
        setAddedByUserId(other.getAddedByUserId());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.whispersystems.textsecuregcm.proto.PendingMember parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.whispersystems.textsecuregcm.proto.PendingMember) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.whispersystems.textsecuregcm.proto.Member member_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.Member, org.whispersystems.textsecuregcm.proto.Member.Builder, org.whispersystems.textsecuregcm.proto.MemberOrBuilder> memberBuilder_;
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     * @return Whether the member field is set.
     */
    public boolean hasMember() {
      return memberBuilder_ != null || member_ != null;
    }
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     * @return The member.
     */
    public org.whispersystems.textsecuregcm.proto.Member getMember() {
      if (memberBuilder_ == null) {
        return member_ == null ? org.whispersystems.textsecuregcm.proto.Member.getDefaultInstance() : member_;
      } else {
        return memberBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     */
    public Builder setMember(org.whispersystems.textsecuregcm.proto.Member value) {
      if (memberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        member_ = value;
        onChanged();
      } else {
        memberBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     */
    public Builder setMember(
        org.whispersystems.textsecuregcm.proto.Member.Builder builderForValue) {
      if (memberBuilder_ == null) {
        member_ = builderForValue.build();
        onChanged();
      } else {
        memberBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     */
    public Builder mergeMember(org.whispersystems.textsecuregcm.proto.Member value) {
      if (memberBuilder_ == null) {
        if (member_ != null) {
          member_ =
            org.whispersystems.textsecuregcm.proto.Member.newBuilder(member_).mergeFrom(value).buildPartial();
        } else {
          member_ = value;
        }
        onChanged();
      } else {
        memberBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     */
    public Builder clearMember() {
      if (memberBuilder_ == null) {
        member_ = null;
        onChanged();
      } else {
        member_ = null;
        memberBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     */
    public org.whispersystems.textsecuregcm.proto.Member.Builder getMemberBuilder() {
      
      onChanged();
      return getMemberFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     */
    public org.whispersystems.textsecuregcm.proto.MemberOrBuilder getMemberOrBuilder() {
      if (memberBuilder_ != null) {
        return memberBuilder_.getMessageOrBuilder();
      } else {
        return member_ == null ?
            org.whispersystems.textsecuregcm.proto.Member.getDefaultInstance() : member_;
      }
    }
    /**
     * <pre>
     * The “invited” member
     * </pre>
     *
     * <code>.GroupsProtos.Member member = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.whispersystems.textsecuregcm.proto.Member, org.whispersystems.textsecuregcm.proto.Member.Builder, org.whispersystems.textsecuregcm.proto.MemberOrBuilder> 
        getMemberFieldBuilder() {
      if (memberBuilder_ == null) {
        memberBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.whispersystems.textsecuregcm.proto.Member, org.whispersystems.textsecuregcm.proto.Member.Builder, org.whispersystems.textsecuregcm.proto.MemberOrBuilder>(
                getMember(),
                getParentForChildren(),
                isClean());
        member_ = null;
      }
      return memberBuilder_;
    }

    private com.google.protobuf.ByteString addedByUserId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The UID who invited this member
     * </pre>
     *
     * <code>bytes addedByUserId = 2;</code>
     * @return The addedByUserId.
     */
    @Override
    public com.google.protobuf.ByteString getAddedByUserId() {
      return addedByUserId_;
    }
    /**
     * <pre>
     * The UID who invited this member
     * </pre>
     *
     * <code>bytes addedByUserId = 2;</code>
     * @param value The addedByUserId to set.
     * @return This builder for chaining.
     */
    public Builder setAddedByUserId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addedByUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The UID who invited this member
     * </pre>
     *
     * <code>bytes addedByUserId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddedByUserId() {
      
      addedByUserId_ = getDefaultInstance().getAddedByUserId();
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * The time the invitation occurred
     * </pre>
     *
     * <code>uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * The time the invitation occurred
     * </pre>
     *
     * <code>uint64 timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The time the invitation occurred
     * </pre>
     *
     * <code>uint64 timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GroupsProtos.PendingMember)
  }

  // @@protoc_insertion_point(class_scope:GroupsProtos.PendingMember)
  private static final org.whispersystems.textsecuregcm.proto.PendingMember DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.proto.PendingMember();
  }

  public static org.whispersystems.textsecuregcm.proto.PendingMember getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PendingMember>
      PARSER = new com.google.protobuf.AbstractParser<PendingMember>() {
    @Override
    public PendingMember parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PendingMember(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PendingMember> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PendingMember> getParserForType() {
    return PARSER;
  }

  @Override
  public org.whispersystems.textsecuregcm.proto.PendingMember getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

