// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.whispersystems.textsecuregcm.proto;

public interface PendingMemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupsProtos.PendingMember)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The “invited” member
   * </pre>
   *
   * <code>.GroupsProtos.Member member = 1;</code>
   * @return Whether the member field is set.
   */
  boolean hasMember();
  /**
   * <pre>
   * The “invited” member
   * </pre>
   *
   * <code>.GroupsProtos.Member member = 1;</code>
   * @return The member.
   */
  org.whispersystems.textsecuregcm.proto.Member getMember();
  /**
   * <pre>
   * The “invited” member
   * </pre>
   *
   * <code>.GroupsProtos.Member member = 1;</code>
   */
  org.whispersystems.textsecuregcm.proto.MemberOrBuilder getMemberOrBuilder();

  /**
   * <pre>
   * The UID who invited this member
   * </pre>
   *
   * <code>bytes addedByUserId = 2;</code>
   * @return The addedByUserId.
   */
  com.google.protobuf.ByteString getAddedByUserId();

  /**
   * <pre>
   * The time the invitation occurred
   * </pre>
   *
   * <code>uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
